exec(open('tests/test_sandbox.py').read().split('async def boot')[0])
S = "__grasp.strike"
STATE = "(() => { const s = " + S + ", b = s.ball; return { z: b ? b.z : null, x: b ? b.x : null, y: b ? b.y : null, dir: b ? b.dir : 0, sup: !!(b && b.super), speed: s.speed, pace: s.pace, lives: s.lives, score: s.score, over: s.over, power: s.power, hits: s.hits, misses: s.misses, serves: s.serves, bounces: s.bounces, best: s.best }; })()"
PIX = "((x, y) => { const d = ctx.getImageData(Math.round(x * DPR), Math.round(y * DPR), 1, 1).data; return [d[0], d[1], d[2]]; })"
ROWS = "new Set([...document.querySelectorAll('.modes button')].map(b => Math.round(b.getBoundingClientRect().top / 20))).size"  # the pressed card is lifted 2 px
FITS = "(() => { const bs = [...document.querySelectorAll('.modes button')]; const a = document.querySelector('#start a.link').getBoundingClientRect(); return bs.length === 5 && bs.every(b => b.scrollWidth <= b.clientWidth + 1 && b.getBoundingClientRect().right <= innerWidth && b.getBoundingClientRect().left >= 0) && a.bottom <= innerHeight && a.width > 0; })()"
TOUCH_JS = """
window.touchAt = (t, x, y) => document.getElementById('stage').dispatchEvent(new PointerEvent(t, { pointerId: 7, pointerType: 'touch', isPrimary: true, clientX: x, clientY: y, bubbles: true, cancelable: true, button: 0, buttons: 1 }));
"""
# park an incoming ball at HIT_Z right under the cursor at (x, y); dx px of hand travel in the last ~60 ms sets the hand speed
def hit_js(x, y, dx=0):
    return f"(() => {{ const now = performance.now(); if ({dx}) {{ cursor.history.length = 0; cursor.history.push({{ t: now - 60, x: {x} - {dx}, y: {y} }}, {{ t: now, x: {x}, y: {y} }}); }} {S}.setBallZ(__grasp.CONFIG.STRIKE_HIT_Z, {x}, {y}); }})()"
async def miss(page):
    await page.evaluate(f"{S}.setBallZ(4, innerWidth * 0.5, innerHeight * 0.5)"); await page.wait_for_timeout(250)

async def main():
    async with async_playwright() as p:
        b = await p.chromium.launch(args=['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream'])
        # --- mouse, desktop ---
        ctx = await b.new_context(viewport={'width':1280,'height':800}); page = await ctx.new_page(); await routes(page); errs=[]
        page.on('pageerror', lambda e: errs.append(str(e))); await page.add_init_script(INIT)
        await page.goto('http://localhost:8765/index.html'); await page.wait_for_timeout(600)
        check('desktop: 5 mode cards in one row fit', await page.evaluate(FITS) and await page.evaluate(ROWS) == 1)
        await page.click('.modes button[data-mode=strike]')
        check('menu shows strike selected + description', await page.evaluate("document.querySelector('[data-mode=strike]').getAttribute('aria-pressed')==='true' && $('modeDesc').textContent.includes('corridor')"))
        check('mode cycle includes strike', await page.evaluate("MODE_NEXT.busy === 'strike' && MODE_NEXT.strike === 'sandbox'"))
        cfg = await page.evaluate("({ zf: __grasp.CONFIG.STRIKE_Z_FAR, hz: __grasp.CONFIG.STRIKE_HIT_Z, base: __grasp.CONFIG.STRIKE_BASE_SPEED, max: __grasp.CONFIG.STRIKE_MAX_SPEED, lives: __grasp.CONFIG.STRIKE_LIVES, sup: __grasp.CONFIG.STRIKE_SUPER_SPEED })")
        check('CONFIG has the strike constants', all(v > 0 for v in cfg.values()) and cfg['hz'] < cfg['zf'] and cfg['base'] < cfg['max'], cfg)
        await page.click('#mouseBtn'); await page.wait_for_timeout(900)
        st = await page.evaluate(STATE)
        check('strike mode starts: ball served from the far end, 3 lives, score 0', await page.evaluate("gameMode") == 'strike' and st['z'] is not None and st['z'] > cfg['zf'] * 0.7 and st['lives'] == cfg['lives'] and st['score'] == 0 and st['dir'] == 1, st)
        check('strike.walls list exists for step 2', await page.evaluate(f"Array.isArray({S}.walls)"))
        z0 = st['z']; await page.wait_for_timeout(250); z1 = await page.evaluate(f"{S}.ball.z")
        check('ball approaches: z decreases at the base speed', z0 - z1 > 150 and z0 - z1 < 600, [z0, z1])
        # corridor + ball pixels (the mouse is present, parked low so the hand sprite stays clear of the probes)
        await page.mouse.move(640, 600); await page.wait_for_timeout(150)
        await page.evaluate(f"{S}.setBallZ(900, 200, 700); window.__keepWalls = {S}.walls.splice(0)"); await page.wait_for_timeout(50)  # brick walls set aside: they stand in front of the vanishing point
        floor = await page.evaluate(PIX + "(640, 796)"); far = await page.evaluate(PIX + "(640, 368)"); wall = await page.evaluate(PIX + "(6, 400)")
        check('corridor drawn: bright floor near the player, dark fog at the vanishing point, side wall', floor[2] > floor[0] and floor[2] > 60 and sum(far) < sum(floor) and wall[2] > wall[0], [floor, far, wall])
        await page.evaluate(f"{S}.walls.push(...window.__keepWalls)")
        await page.evaluate(f"{S}.setBallZ(900, 640, 380)"); await page.wait_for_timeout(50)
        bpx = await page.evaluate(PIX + "(640, 380)")
        check('ball drawn as a coral sphere', bpx[0] > 170 and bpx[0] > bpx[2] + 40, bpx)
        await page.screenshot(path='tests/out/strike_desktop.png')
        # hit: cursor parked on the ball, hand still = soft
        await page.evaluate(hit_js(640, 600)); await page.wait_for_timeout(120)
        st = await page.evaluate(STATE)
        check('cursor on the ball at HIT_Z: hit, +1, direction reversed', st['dir'] == -1 and st['score'] == 1 and st['hits'] == 1 and st['z'] > 0, st)
        check('still hand = soft tier, slow return', st['power'] == 'soft' and st['speed'] < st['pace'], st)
        check('hit: the power meter flashes the tier label', await page.evaluate(f"{S}.ui.tierFlash && {S}.ui.tierFlash.tier === 'soft' && performance.now() - {S}.ui.tierFlash.t < 600"))
        pace0 = st['pace']; w0 = await page.evaluate(f"({{ z: {S}.walls[0].z, n: {S}.walls[0].bricks.length }})")
        await page.wait_for_function(f"{S}.ball && {S}.ball.dir === 1", timeout=4000)
        st = await page.evaluate(STATE); left = await page.evaluate(f"{S}.walls[0].left")
        check('soft return chips one brick off the first wall and bounces straight back', st['z'] < w0['z'] and st['z'] > w0['z'] - 80 and left == w0['n'] - 1 and st['score'] == 2 and st['bounces'] == 0 and st['speed'] == st['pace'], [st, w0, left])
        await page.mouse.move(640, 400); await page.wait_for_timeout(120)
        await page.evaluate(hit_js(640, 400, 130)); await page.wait_for_timeout(120)  # a hard return goes through the walls
        await page.wait_for_function(f"{S}.bounces >= 1", timeout=8000)
        st = await page.evaluate(STATE)
        check('hard return bounces off the far end and comes back 5% faster', st['dir'] == 1 and st['z'] > cfg['zf'] * 0.9 and abs(st['pace'] - pace0 * 1.05) < 1e-6 and st['speed'] == st['pace'] and st['power'] == 'hard', [st, pace0])
        # power tiers from the hand speed over the last 100 ms
        await page.mouse.move(640, 400); await page.wait_for_timeout(120)
        for dx, tier, pts in [(60, 'medium', 2), (130, 'hard', 3), (320, 'super', 6)]:
            s0 = (await page.evaluate(STATE))['score']
            await page.evaluate(hit_js(640, 400, dx)); await page.wait_for_timeout(120)
            st = await page.evaluate(STATE)
            check(f'hand speed {dx}px/60ms -> {tier} tier, +{pts}', st['power'] == tier and st['score'] - s0 == pts and st['dir'] == -1, [st, s0])
        check('SUPER: ball glows and flies back fast', st['sup'] and st['speed'] > st['pace'] * 1.5, st)
        check('faster hand = faster return', await page.evaluate(f"{S}.lastHit.pw") > 0.99)
        await page.wait_for_timeout(60); await page.screenshot(path='tests/out/strike_super.png')
        # lateral direction from where the ball was hit
        await page.evaluate(hit_js(600, 400)); await page.mouse.move(560, 400); await page.wait_for_timeout(30)
        await page.evaluate(hit_js(600, 400)); await page.wait_for_timeout(100)
        check('hit on the left side of the ball sends it right', await page.evaluate(f"{S}.ball.dir === -1 && {S}.ball.vx > 0"), await page.evaluate(STATE))
        # miss
        await page.mouse.move(100, 100); await page.wait_for_timeout(100)
        await miss(page)
        st = await page.evaluate(STATE)
        check('ball passes the cursor: miss, one life lost, red flash', st['lives'] == cfg['lives'] - 1 and st['misses'] == 1 and st['z'] is None and await page.evaluate(f"performance.now() - {S}.flash < 600"), st)
        await page.wait_for_timeout(900)
        st = await page.evaluate(STATE)
        check('new serve ~800 ms after a miss', st['z'] is not None and st['z'] > cfg['zf'] * 0.7 and st['serves'] == 2, st)
        sc = st['score']
        await miss(page); await page.wait_for_timeout(900); await miss(page)
        st = await page.evaluate(STATE); best = await page.evaluate("localStorage.getItem('strikeBest')")
        check('three misses: round over, best saved', st['over'] and st['lives'] == 0 and st['best'] == sc and best == str(sc), [st, best])
        await page.wait_for_timeout(1100); await page.screenshot(path='tests/out/strike_over.png')
        await page.mouse.move(300, 300); await page.mouse.down(); await page.mouse.up(); await page.wait_for_timeout(200)
        st = await page.evaluate(STATE)
        check('tap restarts a fresh round, best kept', not st['over'] and st['lives'] == cfg['lives'] and st['score'] == 0 and st['best'] == sc, st)
        await page.wait_for_timeout(700)
        await page.mouse.move(640, 400); await page.wait_for_timeout(100); await page.evaluate(hit_js(640, 400)); await page.wait_for_timeout(120)
        check('reset button restarts', await page.evaluate(f"{S}.score") > 0 and (await page.click('#resetBtn') or True) and await page.evaluate(f"{S}.score === 0 && {S}.lives === {cfg['lives']} && !{S}.over"))
        await page.click('#hudBtn'); await page.wait_for_timeout(700)
        check('HUD shows strike + lives', 'strike' in await page.inner_text('#hud') and 'lives' in await page.inner_text('#hud'))
        await page.evaluate("__grasp.setGameMode('sandbox')"); await page.wait_for_timeout(300)
        check('switching back to sandbox restores objects', await page.evaluate("gameMode === 'sandbox' && bodies.length === 10"))
        check('mouse: no page errors', not errs, errs); await ctx.close()

        # --- brick walls (step 2), desktop mouse ---
        ctx = await b.new_context(viewport={'width':1280,'height':800}); page = await ctx.new_page(); await routes(page); errs=[]
        page.on('pageerror', lambda e: errs.append(str(e))); await page.add_init_script(INIT)
        await page.goto('http://localhost:8765/index.html'); await page.wait_for_timeout(600)
        await page.click('.modes button[data-mode=strike]'); await page.click('#mouseBtn'); await page.wait_for_timeout(900)
        await page.mouse.move(1200, 760); await page.wait_for_timeout(100)  # hand parked in a corner, clear of the walls
        ws = await page.evaluate(f"{S}.walls.map(w => ({{ z: w.z, n: w.bricks.length, alive: w.bricks.filter(k => k.alive).length, cols: w.cols, rows: w.rows, hp: w.hp, level: w.level }}))")
        gap = await page.evaluate("__grasp.CONFIG.STRIKE_WALL_GAP")
        check('4 walls of live bricks stand at 40% depth and every WALL_GAP after', len(ws) == 4 and all(w['n'] == w['cols'] * w['rows'] >= 12 and w['alive'] == w['n'] and w['hp'] == 1 and w['level'] == 1 for w in ws)
              and abs(ws[0]['z'] - cfg['zf'] * 0.4) < 1 and all(abs(ws[i + 1]['z'] - ws[i]['z'] - gap) < 1 for i in range(3)) and ws[3]['z'] < cfg['zf'], ws)
        check('walls sorted near to far', ws == sorted(ws, key=lambda w: w['z']))
        check('level 1, no debris yet', await page.evaluate(f"{S}.level === 1 && {S}.debris.length === 0"))
        # pixel probe: a brick face at the projected centre of the first wall's top-left brick
        pt = await page.evaluate(f"{S}.brickScreen({S}.walls[0], 0, 0)")
        brick = await page.evaluate(PIX + f"({pt['x']}, {pt['y']})")
        check('first wall drawn: terracotta brick pixel at a projected brick centre', brick[0] > brick[2] + 25 and brick[0] > 80, [pt, brick])
        # soft: one brick, ball bounces back
        s0 = await page.evaluate(f"{S}.score"); w = await page.evaluate(f"{S}.smashTest('soft') && {S}.walls[0].id"); await page.wait_for_timeout(150)
        st = await page.evaluate(STATE); wl = await page.evaluate(f"(() => {{ const w = {S}.walls.find(w => w.id === {w}); return {{ left: w.left, n: w.bricks.length, z: w.z }}; }})()")
        check('soft: 1 brick out, +1, ball bounces back toward the player', wl['left'] == wl['n'] - 1 and st['score'] - s0 == 1 and st['dir'] == 1 and st['z'] < wl['z'] and st['speed'] == st['pace'], [st, wl])
        check('brick fragments fly as 3D debris', await page.evaluate(f"{S}.debris.length") >= 1 and await page.evaluate(f"{S}.debris.every(d => d.z < {wl['z']} && d.vz < 0)"))
        await page.wait_for_timeout(1200)
        check('debris flies past the camera and is culled', await page.evaluate(f"{S}.debris.length") == 0)
        # medium: 3x3 area, ball passes through slower
        s0 = await page.evaluate(f"{S}.score"); await page.evaluate(f"{S}.smashTest('medium')"); await page.wait_for_timeout(150)
        st = await page.evaluate(STATE); wl = await page.evaluate(f"(() => {{ const w = {S}.walls.find(w => w.id === {w}); return {{ left: w.left, n: w.bricks.length, z: w.z }}; }})()")
        check('medium: >= 5 bricks out, ball passes through at reduced speed', wl['n'] - wl['left'] >= 6 and st['score'] - s0 >= 5 and st['dir'] == -1 and st['z'] > wl['z'] and st['speed'] < st['pace'], [st, wl, s0])
        # SUPER: whole wall, bonus, combo on the next wall, fresh walls spawn beyond
        s0 = await page.evaluate(f"{S}.score"); zs = await page.evaluate(f"{S}.walls.map(w => w.z)")
        await page.evaluate(f"{S}.smashTest('super')"); await page.wait_for_timeout(60)
        peak = 0
        for _ in range(12):
            await page.wait_for_timeout(50); peak = max(peak, await page.evaluate(f"{S}.debris.length"))
        st = await page.evaluate(STATE); fl = await page.evaluate(f"{S}.floaters.map(f => f.text)")
        gone = await page.evaluate(f"!{S}.walls.some(w => w.id === {w})"); zs2 = await page.evaluate(f"{S}.walls.map(w => w.z)")
        check('SUPER clears the whole first wall: removed, WALL bonus, +10 x level scored', gone and any('WALL' in f for f in fl) and st['score'] - s0 >= wl['left'] + 10, [st, s0, wl, fl])
        check('SUPER keeps going: second wall smashed with a x2 combo banner', await page.evaluate(f"{S}.ui.lastBanner && {S}.ui.lastBanner.n >= 2") and await page.evaluate(f"{S}.cleared") >= 2, [fl, await page.evaluate(f"{S}.ui.lastBanner")])
        check('new walls spawned beyond the far end, still 4 in the queue', len(zs2) == 4 and max(zs2) > max(zs) and await page.evaluate(f"{S}.walls.every(w => w.left === w.bricks.length)"), [zs, zs2])
        check('debris count capped at 60', 0 < peak <= 60, peak)
        await page.mouse.move(1200, 760); await page.wait_for_timeout(700)
        brick2 = await page.evaluate(PIX + f"({pt['x']}, {pt['y']})")
        check('first wall gone: corridor pixel where the brick was', brick2[2] >= brick2[0] and sum(brick2) < 200, [brick, brick2])
        await page.wait_for_function(f"{S}.ball && {S}.ball.dir === 1 && !{S}.ball.super", timeout=4000)
        check('SUPER ends at the far end: ball returns at the normal pace, not super', await page.evaluate(f"{S}.speed === {S}.pace"))
        # level: every 5 walls the bricks get tougher and change colour
        await page.evaluate(f"{S}.cleared = 4; {S}.walls.forEach(w => (w.pz = w.z = Math.min(w.z, 1200)))")
        await page.evaluate(f"{S}.smashTest('super')"); await page.wait_for_timeout(120)
        lv = await page.evaluate(f"({{ level: {S}.level, cleared: {S}.cleared, hp: Math.max(...{S}.walls.map(w => w.hp)), lvls: {S}.walls.map(w => w.level) }})")
        check('level 2 after 5 walls: new walls have 2-hp bricks', lv['level'] == 2 and lv['cleared'] >= 5 and lv['hp'] == 2 and 2 in lv['lvls'], lv)
        await page.wait_for_function(f"{S}.ball && {S}.ball.dir === 1", timeout=4000); await page.wait_for_timeout(300)
        await page.evaluate(f"{S}.walls.forEach(w => (w.pz = w.z = Math.max(w.z, 1000)))")
        w2 = await page.evaluate(f"(() => {{ const w = {S}.walls.find(w => w.hp === 2 && w.left === w.bricks.length); w.pz = w.z = 960; {S}.walls.sort((a, b) => a.z - b.z); return w.id; }})()")
        await page.evaluate(f"{S}.smashTest('soft')"); await page.wait_for_timeout(150)
        cr = await page.evaluate(f"(() => {{ const w = {S}.walls.find(w => w.id === {w2}); return {{ left: w.left, n: w.bricks.length, cracked: w.bricks.filter(k => k.alive && k.hp < w.hp).length, dir: {S}.ball.dir }}; }})()")
        check('a soft hit only cracks a 2-hp brick and still bounces back', cr['left'] == cr['n'] and cr['cracked'] == 1 and cr['dir'] == 1, cr)
        await page.evaluate(f"{S}.walls.find(w => w.id === {w2}).pz = 960"); await page.evaluate(f"{S}.smashTest('hard')"); await page.wait_for_timeout(150)
        cr = await page.evaluate(f"(() => {{ const w = {S}.walls.find(w => w.id === {w2}); return {{ left: w.left, n: w.bricks.length, dir: {S}.ball.dir }}; }})()")
        check('a hard hit knocks 2-hp bricks out and passes', cr['n'] - cr['left'] >= 9 and cr['dir'] == -1, cr)
        await page.wait_for_timeout(200); await page.screenshot(path='tests/out/strike2_desktop.png')
        check('walls: no page errors', not errs, errs); await ctx.close()

        # --- in-game UI (step 3): HUD card, power meter, combo banner, serve cue, round-over card ---
        ctx = await b.new_context(viewport={'width':1280,'height':800}); page = await ctx.new_page(); await routes(page); errs=[]
        page.on('pageerror', lambda e: errs.append(str(e))); await page.add_init_script(INIT)
        await page.goto('http://localhost:8765/index.html'); await page.wait_for_timeout(600)
        await page.click('.modes button[data-mode=strike]'); await page.click('#mouseBtn'); await page.wait_for_timeout(900)
        await page.mouse.move(1200, 760); await page.wait_for_timeout(200)
        chrome = await page.evaluate("document.querySelector('.chrome').getBoundingClientRect().bottom"); hud = await page.evaluate(f"{S}.ui.hud")
        check('HUD card sits below the chrome buttons and fits the screen', hud and hud['y'] >= chrome and hud['x'] >= 0 and hud['x'] + hud['w'] <= 1280 and hud['h'] >= 48, [hud, chrome])
        rim = await page.evaluate(PIX + f"({hud['x'] + hud['w'] / 2}, {hud['y']})"); above = await page.evaluate(PIX + f"({hud['x'] + hud['w'] / 2}, {hud['y'] - 4})")
        check('HUD card rim drawn (a lighter line than the corridor above it)', sum(rim) > sum(above) + 30, [rim, above])
        hearts = await page.evaluate(f"{S}.ui.hearts"); hp = await page.evaluate(PIX + f"({hearts[0]['x']}, {hearts[0]['y']})")
        check('three full hearts on the card', len(hearts) == 3 and hp[0] > 170 and hp[0] > hp[2] + 60 and all(hud['y'] < h['y'] < hud['y'] + hud['h'] for h in hearts), [hearts, hp])
        await page.evaluate(f"{S}.score += 100; {S}.ui.scoreAt = performance.now()"); await page.wait_for_timeout(60)
        shown = await page.evaluate(f"{S}.ui.shown")
        check('score counts up over time rather than jumping', 0 < shown < 100, shown)
        await page.wait_for_timeout(900)
        check('count-up settles on the score', await page.evaluate(f"{S}.ui.shown === {S}.score && Math.round({S}.ui.shown) === 100"))
        # power meter: fills with the hand speed before any hit, live tier name, back to empty when the hand rests
        await page.mouse.move(640, 600); await page.wait_for_timeout(700)
        m0 = await page.evaluate(f"{S}.ui.meter")
        await page.evaluate("(() => { const now = performance.now(); cursor.history.length = 0; cursor.history.push({ t: now - 60, x: 440, y: 600 }, { t: now, x: 640, y: 600 }); })()"); await page.wait_for_timeout(50)
        m1 = await page.evaluate(f"({{ v: {S}.ui.meter, tier: {S}.ui.meterTier }})")
        await page.wait_for_timeout(700); m2 = await page.evaluate(f"{S}.ui.meter")
        check('meter follows the hand speed: empty at rest, high after a fast move, empty again', m0 < 0.05 and m1['v'] > 0.4 and m1['tier'] in ('hard', 'super') and m2 < 0.08, [m0, m1, m2])
        await page.evaluate(hit_js(640, 600, 60)); await page.wait_for_timeout(100)
        tf = await page.evaluate(f"({{ tier: {S}.ui.tierFlash.tier, age: performance.now() - {S}.ui.tierFlash.t, txt: {S}.floaters.map(f => f.text) }})")
        check('medium hit: tier label flashes on the meter, the floater only shows the points', tf['tier'] == 'medium' and tf['age'] < 600 and any(x == '+2' for x in tf['txt']) and not any('Medium' in x for x in tf['txt']), tf)
        await page.screenshot(path='tests/out/strike_ui_desktop.png')
        # combo banner on the second SUPER wall
        await page.mouse.move(1200, 760); await page.wait_for_timeout(700)
        await page.evaluate(f"{S}.smashTest('super')")
        await page.wait_for_function(f"{S}.ui.banner && {S}.ui.banner.n >= 2", timeout=4000)
        bn = await page.evaluate(f"({{ n: {S}.ui.banner.n, age: performance.now() - {S}.ui.banner.t }})")
        check('SUPER second wall: combo banner active', bn['n'] >= 2 and bn['age'] < 900, bn)
        await page.wait_for_timeout(200); await page.screenshot(path='tests/out/strike_ui_combo.png')
        await page.wait_for_function(f"{S}.ball && {S}.ball.dir === 1", timeout=5000)
        # miss: lost heart shakes then stays hollow; serve cue before the next ball
        lv = await page.evaluate(f"{S}.lives"); await miss(page)
        hl = await page.evaluate(f"{S}.ui.heartLost")
        check('miss: the heart that went hollow is the last full one', hl and hl['i'] == lv - 1 and await page.evaluate(f"{S}.lives") == lv - 1, [hl, lv])
        await page.wait_for_timeout(200)
        cue = await page.evaluate(f"({{ k: {S}.ui.cue, cued: {S}.cued, ball: !!{S}.ball }})")
        check('serve cue: ring at the far end (+ whoosh) 500 ms before the serve', cue['k'] is not None and 0 <= cue['k'] < 1 and cue['cued'] and not cue['ball'], cue)
        await page.wait_for_timeout(500)
        hearts = await page.evaluate(f"{S}.ui.hearts"); h0 = await page.evaluate(PIX + f"({hearts[0]['x']}, {hearts[0]['y']})"); h2 = await page.evaluate(PIX + f"({hearts[hl['i']]['x']}, {hearts[hl['i']]['y']})")
        check('hearts: first still red, the lost one hollow after the miss', h0[0] > 170 and h0[0] > h0[2] + 60 and h2[0] < 120, [h0, h2])
        # round over card: NEW BEST ribbon, stats, buttons
        await miss(page); await page.wait_for_timeout(900); await miss(page)
        await page.wait_for_function(f"{S}.over && {S}.ui.buttons", timeout=3000); await page.wait_for_timeout(600)
        ov = await page.evaluate(f"({{ nb: {S}.ui.newBest, best: {S}.best, score: {S}.score, rb: {S}.ui.ribbon, bt: {S}.ui.buttons, hits: {S}.hits, walls: {S}.cleared, combo: {S}.bestCombo }})")
        rbp = await page.evaluate(PIX + f"({ov['rb']['x']}, {ov['rb']['y']})") if ov['rb'] else None
        check('round over with a NEW BEST ribbon (saffron pixel on the card corner)', ov['nb'] and ov['best'] == ov['score'] > 0 and rbp and rbp[0] > 200 and rbp[1] > 140 and rbp[2] < 130, [ov, rbp])
        check('stats for the card: hits, walls, best combo', ov['hits'] >= 1 and ov['walls'] >= 2 and ov['combo'] >= 2, ov)
        bt = ov['bt']
        check('two buttons on the card, side by side, on screen', bt['again']['w'] > 100 and bt['home']['w'] > 100 and bt['again']['y'] == bt['home']['y'] and bt['again']['x'] + bt['again']['w'] < bt['home']['x'] and bt['home']['x'] + bt['home']['w'] <= 1280, bt)
        ab = await page.evaluate(PIX + f"({bt['again']['x'] + 12}, {bt['again']['y'] + bt['again']['h'] / 2})")
        check('Play again button is saffron', ab[0] > 200 and ab[1] > 150 and ab[2] < 130, ab)
        await page.screenshot(path='tests/out/strike_ui_over.png')
        await page.mouse.click(bt['again']['x'] + bt['again']['w'] / 2, bt['again']['y'] + bt['again']['h'] / 2); await page.wait_for_timeout(200)
        st = await page.evaluate(STATE)
        check('click Play again: fresh round, best kept', not st['over'] and st['score'] == 0 and st['lives'] == cfg['lives'] and st['best'] == ov['best'] and await page.evaluate(f"{S}.ui.buttons === null"), st)
        await page.mouse.move(1200, 760); await page.wait_for_timeout(700)
        for _ in range(3): await miss(page); await page.wait_for_timeout(900)
        await page.wait_for_function(f"{S}.over && {S}.ui.buttons", timeout=3000); await page.wait_for_timeout(600)
        check('a worse round: no NEW BEST', await page.evaluate(f"!{S}.ui.newBest && {S}.ui.ribbon === null"))
        # point gesture (right button) dwelling on Home for 400 ms presses it via the filling ring
        bt = await page.evaluate(f"{S}.ui.buttons")
        await page.mouse.move(bt['home']['x'] + bt['home']['w'] / 2, bt['home']['y'] + bt['home']['h'] / 2); await page.wait_for_timeout(100)
        check('hovering the Home button highlights it', await page.evaluate(f"{S}.ui.hover") == 'home')
        await page.mouse.down(button='right'); await page.wait_for_timeout(200)
        dw = await page.evaluate(f"({S}.ui.dwell && {S}.ui.dwell.key)"); still = await page.evaluate("mode")
        await page.wait_for_timeout(400); await page.mouse.up(button='right')
        check('point held on Home: dwell ring fills, then Home fires (no instant restart)', dw == 'home' and still == 'mouse' and await page.evaluate("mode === 'none' && !$('start').hidden"), [dw, still, await page.evaluate("mode")])
        # tap on Home from a fresh round-over
        await page.click('#mouseBtn'); await page.wait_for_timeout(500); await page.mouse.move(1200, 760); await page.wait_for_timeout(300)
        for _ in range(3): await miss(page); await page.wait_for_timeout(900)
        await page.wait_for_function(f"{S}.over && {S}.ui.buttons", timeout=3000); await page.wait_for_timeout(600)
        bt = await page.evaluate(f"{S}.ui.buttons")
        await page.mouse.click(bt['home']['x'] + bt['home']['w'] / 2, bt['home']['y'] + bt['home']['h'] / 2); await page.wait_for_timeout(200)
        check('click Home: back to the start screen', await page.evaluate("mode === 'none' && !$('start').hidden && document.body.classList.contains('home')"))
        check('ui: no page errors', not errs, errs); await ctx.close()

        # --- camera stub, desktop: an open hand on the ball hits it ---
        ctx = await b.new_context(permissions=['camera'], viewport={'width':1280,'height':800}); page = await ctx.new_page(); await routes(page); errs=[]
        page.on('pageerror', lambda e: errs.append(str(e))); await page.add_init_script(INIT + HAND_JS)
        await page.goto('http://localhost:8765/index.html'); await page.wait_for_timeout(600)
        await page.click('.modes button[data-mode=strike]'); await page.click('#camBtn')
        await page.wait_for_function("mode === 'camera'", timeout=15000)
        await page.evaluate("window.__handFor = () => handAt(640, 400, 0.8)"); await page.wait_for_timeout(900)
        cur = await page.evaluate("[gesture, cursor.x, cursor.y, cursor.present]")
        check('camera: open hand tracked as the cursor', cur[0] == 'open' and cur[3] and abs(cur[1] - 640) < 30 and abs(cur[2] - 400) < 30, cur)
        await page.evaluate(f"{S}.setBallZ(__grasp.CONFIG.STRIKE_HIT_Z, cursor.x, cursor.y)"); await page.wait_for_timeout(120)
        st = await page.evaluate(STATE)
        check('camera: open hand at the ball position hits it', st['dir'] == -1 and st['score'] >= 1, st)
        await page.wait_for_timeout(40); await page.screenshot(path='tests/out/strike_camera.png')
        await page.evaluate("window.__handFor = () => null"); await page.wait_for_timeout(700)
        z0 = await page.evaluate(f"{S}.ball && {S}.ball.z"); await page.wait_for_timeout(300); z1 = await page.evaluate(f"{S}.ball && {S}.ball.z")
        check('camera: the ball waits while the hand is missing', await page.evaluate("noHandShown") and z0 == z1, [z0, z1])
        check('camera: no page errors', not errs, errs); await ctx.close()

        # --- phone (touch), English + Hebrew ---
        for he in (False, True):
            tag = 'he' if he else 'en'
            ctx = await b.new_context(viewport={'width':360,'height':740}, device_scale_factor=3, is_mobile=True, has_touch=True); page = await ctx.new_page(); await routes(page); errs=[]
            page.on('pageerror', lambda e: errs.append(str(e))); await page.add_init_script(INIT + TOUCH_JS)
            await page.goto('http://localhost:8765/index.html'); await page.wait_for_timeout(600)
            if he: await page.tap('#startLang'); await page.wait_for_timeout(100)
            rows = await page.evaluate(ROWS)
            check(tag + ' phone: 5 mode cards (3 + 2) and link fit', await page.evaluate(FITS) and rows == 2, rows)
            await page.screenshot(path='tests/out/strike_start_' + tag + '.png')
            await page.tap('.modes button[data-mode=strike]')
            check(tag + ' phone: strike description', await page.evaluate("$('modeDesc').textContent.includes(" + ("'מסדרון'" if he else "'corridor'") + ")"))
            await page.tap('#mouseBtn'); await page.wait_for_timeout(900)
            st = await page.evaluate(STATE)
            check(tag + ' phone: ball served', st['z'] is not None and st['lives'] == 3, st)
            await page.evaluate("touchAt('pointerdown', 180, 360)"); await page.wait_for_timeout(80)
            await page.evaluate(f"{S}.setBallZ(700, 180, 360)"); await page.wait_for_timeout(50)
            await page.screenshot(path='tests/out/strike_phone_' + tag + '.png')
            await page.evaluate(hit_js(180, 360, 60)); await page.wait_for_timeout(120)  # 1 px/ms at the phone's 0.55 scale = hard
            st = await page.evaluate(STATE)
            check(tag + ' phone: a finger on the ball hits it', st['dir'] == -1 and st['score'] >= 1 and st['lives'] == 3, st)
            await page.screenshot(path='tests/out/strike_ui_' + tag + '.png')
            hud = await page.evaluate(f"{S}.ui.hud"); chrome = await page.evaluate("document.querySelector('.chrome').getBoundingClientRect().bottom")
            check(tag + ' phone: HUD card under the chrome, inside 360 px', hud['y'] >= chrome and hud['x'] >= 8 and hud['x'] + hud['w'] <= 352, [hud, chrome])
            check(tag + ' phone: tier flash on the meter after the hit', await page.evaluate(f"{S}.ui.tierFlash && {S}.ui.tierFlash.tier === 'hard'"))
            await page.evaluate("touchAt('pointerup', 180, 360)"); await page.wait_for_timeout(300)
            check(tag + ' phone: hint mentions the walls', ('לבנים' if he else 'walls') in await page.inner_text('#hint'))
            s0 = await page.evaluate(f"{S}.score"); await page.evaluate(f"{S}.smashTest('super')"); await page.wait_for_timeout(140)
            await page.screenshot(path='tests/out/strike2_phone_' + tag + '.png')
            check(tag + ' phone: SUPER smash clears a wall with debris', await page.evaluate(f"{S}.cleared") >= 1 and await page.evaluate(f"{S}.debris.length") > 0 and await page.evaluate(f"{S}.score") - s0 >= 20)
            await page.wait_for_timeout(300)
            for _ in range(3): await miss(page); await page.wait_for_timeout(900)
            check(tag + ' phone: round over after 3 misses', await page.evaluate(f"{S}.over"))
            await page.wait_for_timeout(600); await page.screenshot(path='tests/out/strike_over_' + tag + '.png')
            bt = await page.evaluate(f"{S}.ui.buttons")
            check(tag + ' phone: card buttons fit the screen' + (', Play again on the right' if he else ''), bt and all(b['x'] >= 8 and b['x'] + b['w'] <= 352 and b['h'] >= 44 for b in bt.values()) and ((bt['again']['x'] > bt['home']['x']) == he), bt)
            check(tag + ' phone: no page errors', not errs, errs); await ctx.close()
        await b.close()
    print('FAILURES:', check.fails)
asyncio.run(main()); srv.terminate()
if check.fails: sys.exit(1)
