exec(open('tests/test_sandbox.py').read().split('async def boot')[0])
S = "__grasp.strike"
STATE = "(() => { const s = " + S + ", b = s.ball; return { z: b ? b.z : null, x: b ? b.x : null, y: b ? b.y : null, dir: b ? b.dir : 0, sup: !!(b && b.super), speed: s.speed, pace: s.pace, lives: s.lives, score: s.score, over: s.over, power: s.power, hits: s.hits, misses: s.misses, serves: s.serves, bounces: s.bounces, best: s.best }; })()"
PIX = "((x, y) => { const d = ctx.getImageData(Math.round(x * DPR), Math.round(y * DPR), 1, 1).data; return [d[0], d[1], d[2]]; })"
ROWS = "new Set([...document.querySelectorAll('.modes button')].map(b => Math.round(b.getBoundingClientRect().top / 20))).size"  # the pressed card is lifted 2 px
FITS = "(() => { const bs = [...document.querySelectorAll('.modes button')], m = document.querySelector('.modes').getBoundingClientRect(); const a = document.querySelector('#start a.link').getBoundingClientRect(); const sel = document.querySelector('.modes button[aria-pressed=true]').getBoundingClientRect(); return bs.length === 5 && bs.every(b => b.scrollWidth <= b.clientWidth + 1) && m.right <= innerWidth && m.left >= 0 && sel.right <= innerWidth && sel.left >= 0 && a.bottom <= innerHeight && a.width > 0; })()"  # phones: a scrollable snap row; the selected card is in view
TOUCH_JS = """
window.touchAt = (t, x, y) => document.getElementById('stage').dispatchEvent(new PointerEvent(t, { pointerId: 7, pointerType: 'touch', isPrimary: true, clientX: x, clientY: y, bubbles: true, cancelable: true, button: 0, buttons: 1 }));
"""
# park an incoming ball at HIT_Z right under the cursor at (x, y); dx px of hand travel in the last ~60 ms sets the hand speed
def hit_js(x, y, dx=0):
    return f"(() => {{ const now = performance.now(); if ({dx}) {{ cursor.history.length = 0; cursor.history.push({{ t: now - 60, x: {x} - {dx}, y: {y} }}, {{ t: now, x: {x}, y: {y} }}); }} {S}.setBallZ(__grasp.CONFIG.STRIKE_HIT_Z, {x}, {y}); }})()"
async def miss(page):  # park the ball just past the player's plane with no hand near it (and no recent cursor path near it): a miss on both difficulties (Easy still allows a late slap down to -HIT_Z)
    await page.evaluate(f"cursor.history.length = 0; {S}.setBallZ(-__grasp.CONFIG.STRIKE_HIT_Z * 0.7, innerWidth * 0.5, innerHeight * 0.5)"); await page.wait_for_timeout(250)
async def miss_out(page, n):  # n misses, a serve apart
    for _ in range(n): await miss(page); await page.wait_for_timeout(900)

async def main():
    async with async_playwright() as p:
        b = await p.chromium.launch(args=['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream'])
        # --- mouse, desktop ---
        ctx = await b.new_context(viewport={'width':1280,'height':800}); page = await ctx.new_page(); await routes(page); errs=[]
        page.on('pageerror', lambda e: errs.append(str(e))); await page.add_init_script(INIT)
        await page.goto('http://localhost:8765/index.html'); await page.wait_for_timeout(600)
        check('desktop: 5 mode cards in one row fit', await page.evaluate(FITS) and await page.evaluate(ROWS) == 1)
        await page.click('.modes button[data-mode=strike]')
        check('menu shows strike selected + description', await page.evaluate("document.querySelector('[data-mode=strike]').getAttribute('aria-pressed')==='true' && $('modeDesc').textContent.includes('corridor')"))
        check('mode cycle includes strike', await page.evaluate("MODE_NEXT.busy === 'strike' && MODE_NEXT.strike === 'sandbox'"))
        cfg = await page.evaluate("({ zf: __grasp.CONFIG.STRIKE_Z_FAR, hz: __grasp.CONFIG.STRIKE_HIT_Z, base: __grasp.CONFIG.STRIKE_BASE_SPEED, max: __grasp.CONFIG.STRIKE_MAX_SPEED, lives: __grasp.CONFIG.STRIKE_LIVES, sup: __grasp.CONFIG.STRIKE_SUPER_SPEED })")
        check('CONFIG has the strike constants', all(v > 0 for v in cfg.values()) and cfg['hz'] < cfg['zf'] and cfg['base'] < cfg['max'], cfg)
        await page.click('#mouseBtn'); await page.wait_for_timeout(900)
        st = await page.evaluate(STATE)
        check('strike mode starts: ball served from the far end, 3 lives, score 0', await page.evaluate("gameMode") == 'strike' and st['z'] is not None and st['z'] > cfg['zf'] * 0.7 and st['lives'] == cfg['lives'] and st['score'] == 0 and st['dir'] == 1, st)
        check('strike.walls list exists for step 2', await page.evaluate(f"Array.isArray({S}.walls)"))
        z0 = st['z']; await page.wait_for_timeout(250); z1 = await page.evaluate(f"{S}.ball.z")
        check('ball approaches: z decreases at the base speed', z0 - z1 > 100 and z0 - z1 < 600, [z0, z1])
        # corridor + ball pixels (the mouse is present, parked low so the hand sprite stays clear of the probes)
        await page.mouse.move(640, 600); await page.wait_for_timeout(150)
        await page.evaluate(f"{S}.setBallZ(900, 200, 700); window.__keepWalls = {S}.walls.splice(0)"); await page.wait_for_timeout(50)  # brick walls set aside: they stand in front of the vanishing point
        floor = await page.evaluate(PIX + "(640, 796)"); far = await page.evaluate(PIX + "(640, 368)"); wall = await page.evaluate(PIX + "(6, 400)")
        check('corridor drawn: bright floor near the player, dark fog at the vanishing point, side wall', floor[2] > floor[0] and floor[2] > 60 and sum(far) < sum(floor) and wall[2] > wall[0], [floor, far, wall])
        await page.evaluate(f"{S}.walls.push(...window.__keepWalls)")
        await page.evaluate(f"{S}.setBallZ(900, 640, 380)"); await page.wait_for_timeout(50)
        bpx = await page.evaluate(PIX + "(640, 380)")
        check('ball drawn as a coral sphere', bpx[0] > 170 and bpx[0] > bpx[2] + 40, bpx)
        await page.screenshot(path='tests/out/strike_desktop.png')
        # hit: cursor parked on the ball, hand still = soft
        await page.evaluate(hit_js(640, 600)); await page.wait_for_timeout(120)
        st = await page.evaluate(STATE)
        check('cursor on the ball at HIT_Z: hit, +1, direction reversed', st['dir'] == -1 and st['score'] == 1 and st['hits'] == 1 and st['z'] > 0, st)
        check('still hand = soft tier, slow return', st['power'] == 'soft' and st['speed'] < st['pace'], st)
        check('hit: the power meter flashes the tier label', await page.evaluate(f"{S}.ui.tierFlash && {S}.ui.tierFlash.tier === 'soft' && performance.now() - {S}.ui.tierFlash.t < 600"))
        pace0 = st['pace']; w0 = await page.evaluate(f"({{ z: {S}.walls[0].z, n: {S}.walls[0].bricks.length }})")
        await page.wait_for_function(f"{S}.ball && {S}.ball.dir === 1", timeout=4000)
        st = await page.evaluate(STATE); left = await page.evaluate(f"{S}.walls[0].left")
        check('soft return chips one brick off the first wall and bounces straight back (resting a ball\'s depth in front of it)', st['z'] < w0['z'] and st['z'] > w0['z'] - 100 and left == w0['n'] - 1 and st['score'] == 2 and st['bounces'] == 0 and st['speed'] == st['pace'], [st, w0, left])
        await page.mouse.move(640, 400); await page.wait_for_timeout(120)
        await page.evaluate(hit_js(640, 400, 95)); await page.wait_for_timeout(120)  # a hard return goes through the walls
        await page.wait_for_function(f"{S}.bounces >= 1", timeout=8000)
        st = await page.evaluate(STATE)
        grow = await page.evaluate("__grasp.strikeParams().grow")
        check('hard return bounces off the far end and comes back faster (3% on Easy)', st['dir'] == 1 and st['z'] > cfg['zf'] * 0.9 and abs(st['pace'] - pace0 * grow) < 1e-6 and st['speed'] == st['pace'] and st['power'] == 'hard', [st, pace0, grow])
        # power tiers from the hand speed over the last 100 ms
        await page.mouse.move(640, 400); await page.wait_for_timeout(120)
        for dx, tier, pts in [(50, 'medium', 2), (95, 'hard', 3), (320, 'super', 6)]:  # each sits mid-band: the next frame's rAF timestamp trails performance.now() by 0-16 ms, so the measured speed is dx / 44..60 ms
            s0 = (await page.evaluate(STATE))['score']
            await page.evaluate(hit_js(640, 400, dx)); await page.wait_for_timeout(120)
            st = await page.evaluate(STATE)
            check(f'hand speed {dx}px/60ms -> {tier} tier, +{pts}', st['power'] == tier and st['score'] - s0 == pts and st['dir'] == -1, [st, s0])
        check('SUPER: ball glows and flies back fast', st['sup'] and st['speed'] > st['pace'] * 1.5, st)
        check('faster hand = faster return', await page.evaluate(f"{S}.lastHit.pw") > 0.99)
        await page.wait_for_timeout(60); await page.screenshot(path='tests/out/strike_super.png')
        # lateral direction from where the ball was hit
        await page.evaluate(hit_js(600, 400)); await page.mouse.move(560, 400); await page.wait_for_timeout(30)
        await page.evaluate(hit_js(600, 400)); await page.wait_for_timeout(100)
        check('hit on the left side of the ball sends it right', await page.evaluate(f"{S}.ball.dir === -1 && {S}.ball.vx > 0"), await page.evaluate(STATE))
        # miss
        await page.mouse.move(100, 100); await page.wait_for_timeout(250)
        await miss(page)
        st = await page.evaluate(STATE)
        check('ball passes the cursor: miss, one life lost, red flash', st['lives'] == cfg['lives'] - 1 and st['misses'] == 1 and st['z'] is None and await page.evaluate(f"performance.now() - {S}.flash < 600"), st)
        await page.wait_for_timeout(900)
        st = await page.evaluate(STATE)
        check('new serve ~800 ms after a miss', st['z'] is not None and st['z'] > cfg['zf'] * 0.7 and st['serves'] == 2, st)
        sc = st['score']
        await miss_out(page, cfg['lives'] - 1)
        st = await page.evaluate(STATE); best = await page.evaluate("localStorage.getItem('strikeBest')")
        check('all lives missed: round over, best saved', st['over'] and st['lives'] == 0 and st['best'] == sc and best == str(sc), [st, best])
        await page.wait_for_timeout(1100); await page.screenshot(path='tests/out/strike_over.png')
        await page.mouse.move(300, 300); await page.mouse.down(); await page.mouse.up(); await page.wait_for_timeout(200)
        st = await page.evaluate(STATE)
        check('tap restarts a fresh round, best kept', not st['over'] and st['lives'] == cfg['lives'] and st['score'] == 0 and st['best'] == sc, st)
        await page.wait_for_timeout(700)
        await page.mouse.move(640, 400); await page.wait_for_timeout(100); await page.evaluate(hit_js(640, 400)); await page.wait_for_timeout(120)
        check('reset button restarts', await page.evaluate(f"{S}.score") > 0 and (await page.click('#resetBtn') or True) and await page.evaluate(f"{S}.score === 0 && {S}.lives === {cfg['lives']} && !{S}.over"))
        await page.click('#hudBtn'); await page.wait_for_timeout(700)
        check('HUD shows strike + lives', 'strike' in await page.inner_text('#hud') and 'lives' in await page.inner_text('#hud'))
        # kid-friendly Easy default: 5 lives, slower ball, bigger reach, late slaps, magnet assist; Normal = the old values
        pr = await page.evaluate("__grasp.strikeParams()")
        check('Easy is the default: 5 lives, 0.65 base speed, x2.6 reach + 120 px, late window, magnet 0.5', pr['diff'] == 'easy' and pr['lives'] == 5 and pr['speed'] == 0.65 and pr['radius'] == 2.6 and pr['near'] == 120 and pr['late'] > 0 and pr['magnet'] == 0.5 and pr['hand'] > 1 and pr['grow'] == 1.03 and pr['max'] == 2.2, pr)
        await page.mouse.move(640, 400); await page.wait_for_timeout(150); s0 = await page.evaluate(f"{S}.score")
        await page.evaluate(f"{S}.setBallZ(__grasp.CONFIG.STRIKE_HIT_Z, 760, 400)"); await page.wait_for_timeout(120)
        check('Easy: a hand 120 px from the ball still hits it', await page.evaluate(f"{S}.score") > s0 and await page.evaluate(f"{S}.ball.dir") == -1)
        # a laggy tracker: a cursor that was on the ball ~100 ms before the crossing (and has since moved away) still hits; 300 ms ago is too old
        await page.wait_for_timeout(150); h0 = await page.evaluate(f"{S}.hits")
        await page.mouse.move(400, 400); await page.wait_for_timeout(250); await page.mouse.move(900, 400); await page.wait_for_timeout(70)
        await page.evaluate(f"{S}.setBallZ(__grasp.CONFIG.STRIKE_HIT_Z, 400, 400)"); await page.wait_for_timeout(120)
        check('a cursor that was on the ball 100 ms before the crossing still hits', await page.evaluate(f"{S}.hits") == h0 + 1 and await page.evaluate(f"{S}.ball.dir") == -1, await page.evaluate(STATE))
        await page.wait_for_timeout(150); h0 = await page.evaluate(f"{S}.hits")
        await page.mouse.move(400, 400); await page.wait_for_timeout(250); await page.mouse.move(900, 400); await page.wait_for_timeout(320)
        await page.evaluate(f"{S}.setBallZ(__grasp.CONFIG.STRIKE_HIT_Z, 400, 400)"); await page.wait_for_timeout(120)
        check('a cursor that left the ball 300 ms ago is too old: no hit', await page.evaluate(f"{S}.hits") == h0 and await page.evaluate(f"{S}.ball && {S}.ball.dir") == 1, await page.evaluate(STATE))
        await page.evaluate(f"{S}.setBallZ(1500, 640, 400)"); await page.mouse.move(640, 400); await page.wait_for_timeout(400)  # that ball parked far away again, the hand back on it
        await page.wait_for_timeout(150); s0 = await page.evaluate(f"{S}.score")
        await page.evaluate(f"{S}.setBallZ(-__grasp.CONFIG.STRIKE_HIT_Z * 0.6, 640, 400)"); await page.wait_for_timeout(120)
        check('Easy: a late slap just past the plane still counts', await page.evaluate(f"{S}.score") > s0 and await page.evaluate(f"{S}.misses") == 0)
        await page.wait_for_timeout(150)
        await page.evaluate(f"{S}.setBallZ({cfg['zf'] * 0.2}, 760, 400)"); x0 = (await page.evaluate(f"{S}.ballScreen()"))['x']; await page.wait_for_timeout(160)
        x1 = (await page.evaluate(f"{S}.ballScreen()"))['x']
        check('Easy: magnet assist drifts the ball toward the hand in the last quarter', x0 > 740 and x1 < x0 - 20 and x1 > 640, [x0, x1])
        await page.evaluate("__grasp.setStrikeDiff('normal')"); await page.click('#resetBtn'); await page.wait_for_timeout(300)
        pr = await page.evaluate("__grasp.strikeParams()"); st = await page.evaluate(STATE)
        check('Normal: the previous values, saved in localStorage, 3 lives on reset', pr['lives'] == 3 and pr['speed'] == 1.1 and pr['radius'] == 1.3 and pr['near'] == 0 and pr['late'] == 0 and pr['magnet'] == 0 and pr['grow'] == 1.05 and pr['max'] == 2.8 and st['lives'] == 3 and await page.evaluate("localStorage.getItem('strikeDiff')") == 'normal', [pr, st])
        await page.mouse.move(640, 400); await page.wait_for_timeout(150); s0 = await page.evaluate(f"{S}.score")
        await page.evaluate(f"{S}.setBallZ(__grasp.CONFIG.STRIKE_HIT_Z, 760, 400)"); await page.wait_for_timeout(120)
        check('Normal: 120 px away is a miss, not a hit', await page.evaluate(f"{S}.score") == s0 and await page.evaluate(f"{S}.ball ? {S}.ball.dir === 1 : {S}.misses >= 1"))
        await page.evaluate("__grasp.setStrikeDiff('easy')")
        await page.evaluate("__grasp.setGameMode('sandbox')"); await page.wait_for_timeout(300)
        check('switching back to sandbox restores objects', await page.evaluate("gameMode === 'sandbox' && bodies.length === 10"))
        check('mouse: no page errors', not errs, errs); await ctx.close()

        # --- brick walls (step 2), desktop mouse ---
        ctx = await b.new_context(viewport={'width':1280,'height':800}); page = await ctx.new_page(); await routes(page); errs=[]
        page.on('pageerror', lambda e: errs.append(str(e))); await page.add_init_script(INIT)
        await page.goto('http://localhost:8765/index.html'); await page.wait_for_timeout(600)
        await page.click('.modes button[data-mode=strike]'); await page.click('#mouseBtn'); await page.wait_for_timeout(900)
        await page.mouse.move(1200, 760); await page.wait_for_timeout(100)  # hand parked in a corner, clear of the walls
        ws = await page.evaluate(f"{S}.walls.map(w => ({{ z: w.z, n: w.bricks.length, alive: w.bricks.filter(k => k.alive).length, cols: w.cols, rows: w.rows, hp: w.hp, level: w.level }}))")
        gap = await page.evaluate("__grasp.CONFIG.STRIKE_WALL_GAP")
        check('4 walls of live bricks stand at 40% depth and every WALL_GAP after', len(ws) == 4 and all(w['n'] == w['cols'] * w['rows'] >= 12 and w['alive'] == w['n'] and w['hp'] == 1 and w['level'] == 1 for w in ws)
              and abs(ws[0]['z'] - cfg['zf'] * 0.4) < 1 and all(abs(ws[i + 1]['z'] - ws[i]['z'] - gap) < 1 for i in range(3)) and ws[3]['z'] < cfg['zf'], ws)
        check('walls sorted near to far', ws == sorted(ws, key=lambda w: w['z']))
        check('level 1, no debris yet', await page.evaluate(f"{S}.level === 1 && {S}.debris.length === 0"))
        # pixel probe: a brick face at the projected centre of the first wall's top-left brick
        pt = await page.evaluate(f"{S}.brickScreen({S}.walls[0], 0, 0)")
        brick = await page.evaluate(PIX + f"({pt['x']}, {pt['y']})")
        check('first wall drawn: terracotta brick pixel at a projected brick centre', brick[0] > brick[2] + 25 and brick[0] > 80, [pt, brick])
        # soft: one brick, ball bounces back
        s0 = await page.evaluate(f"{S}.score"); w = await page.evaluate(f"{S}.smashTest('soft') && {S}.walls[0].id"); await page.wait_for_timeout(150)
        st = await page.evaluate(STATE); wl = await page.evaluate(f"(() => {{ const w = {S}.walls.find(w => w.id === {w}); return {{ left: w.left, n: w.bricks.length, z: w.z }}; }})()")
        check('soft: 1 brick out, +1, ball bounces back toward the player', wl['left'] == wl['n'] - 1 and st['score'] - s0 == 1 and st['dir'] == 1 and st['z'] < wl['z'] and st['speed'] == st['pace'], [st, wl])
        check('brick fragments fly as 3D debris', await page.evaluate(f"{S}.debris.length") >= 1 and await page.evaluate(f"{S}.debris.every(d => d.z < {wl['z']} && d.vz < 0)"))
        await page.wait_for_timeout(1200)
        check('debris flies past the camera and is culled', await page.evaluate(f"{S}.debris.length") == 0)
        # medium: 3x3 area, ball passes through slower
        s0 = await page.evaluate(f"{S}.score"); await page.evaluate(f"{S}.smashTest('medium')"); await page.wait_for_timeout(150)
        st = await page.evaluate(STATE); wl = await page.evaluate(f"(() => {{ const w = {S}.walls.find(w => w.id === {w}); return {{ left: w.left, n: w.bricks.length, z: w.z }}; }})()")
        check('medium: >= 5 bricks out, ball passes through at reduced speed', wl['n'] - wl['left'] >= 6 and st['score'] - s0 >= 5 and st['dir'] == -1 and st['z'] > wl['z'] and st['speed'] < st['pace'], [st, wl, s0])
        # SUPER: whole wall, bonus, combo on the next wall, fresh walls spawn beyond
        s0 = await page.evaluate(f"{S}.score"); zs = await page.evaluate(f"{S}.walls.map(w => w.z)")
        await page.evaluate(f"{S}.smashTest('super')"); await page.wait_for_timeout(60)
        peak = 0
        for _ in range(12):
            await page.wait_for_timeout(50); peak = max(peak, await page.evaluate(f"{S}.debris.length"))
        st = await page.evaluate(STATE); fl = await page.evaluate(f"{S}.floaters.map(f => f.text)")
        gone = await page.evaluate(f"!{S}.walls.some(w => w.id === {w})"); zs2 = await page.evaluate(f"{S}.walls.map(w => w.z)")
        check('SUPER clears the whole first wall: removed, WALL bonus, +10 x level scored', gone and any('WALL' in f for f in fl) and st['score'] - s0 >= wl['left'] + 10, [st, s0, wl, fl])
        check('SUPER keeps going: second wall smashed with a x2 combo banner', await page.evaluate(f"{S}.ui.lastBanner && {S}.ui.lastBanner.n >= 2") and await page.evaluate(f"{S}.cleared") >= 2, [fl, await page.evaluate(f"{S}.ui.lastBanner")])
        check('new walls spawned beyond the far end, still 4 in the queue', len(zs2) == 4 and max(zs2) > max(zs) and await page.evaluate(f"{S}.walls.every(w => w.left === w.bricks.length)"), [zs, zs2])
        check('debris count capped at 60', 0 < peak <= 60, peak)
        await page.mouse.move(1200, 760); await page.wait_for_timeout(700)
        await page.evaluate(f"window.__keepBall = {S}.ball; {S}.ball = null; {S}.serveAt = performance.now() + 5000"); await page.wait_for_timeout(60)  # the (slower, Easy) ball and its trail out of the probe
        brick2 = [999, 999, 999]
        for _ in range(6):  # fragments of the smashed walls may still be tumbling past the probe: keep the darkest sample
            px = await page.evaluate(PIX + f"({pt['x']}, {pt['y']})"); brick2 = min(brick2, px, key=sum); await page.wait_for_timeout(60)
        await page.evaluate(f"{S}.ball = window.__keepBall")
        check('first wall gone: corridor pixel where the brick was', brick2[2] >= brick2[0] and sum(brick2) < 200, [brick, brick2])
        await page.wait_for_function(f"{S}.ball && {S}.ball.dir === 1 && !{S}.ball.super", timeout=4000)
        check('SUPER ends at the far end: ball returns at the normal pace, not super', await page.evaluate(f"{S}.speed === {S}.pace"))
        # level: every 5 walls the bricks get tougher and change colour
        await page.evaluate(f"{S}.cleared = 4; {S}.walls.forEach(w => (w.pz = w.z = Math.min(w.z, 1200)))")
        await page.evaluate(f"{S}.smashTest('super')"); await page.wait_for_timeout(120)
        lv = await page.evaluate(f"({{ level: {S}.level, cleared: {S}.cleared, kinds: {S}.walls.map(w => w.kind), lvls: {S}.walls.map(w => w.level), hp2: (() => {{ const w = {S}.spawnWall('brick', 9000); const hp = w.hp; {S}.walls.splice({S}.walls.indexOf(w), 1); return hp; }})() }})")
        check('level 2 after 5 walls: brick walls now have 2-hp bricks (a SUPER ball may clear more walls that slide into its path)', lv['level'] >= 2 and lv['cleared'] >= 5 and lv['level'] in lv['lvls'] and lv['hp2'] == lv['level'], lv)
        await page.wait_for_function(f"{S}.ball && {S}.ball.dir === 1", timeout=4000); await page.wait_for_timeout(300)
        await page.evaluate(f"{S}.setLevel(2); {S}.walls.forEach(w => (w.pz = w.z = Math.max(w.z, 1000)))")  # pinned at level 2 for the 2-hp checks (the ball may have cleared enough for level 3 meanwhile)
        w2 = await page.evaluate(f"(() => {{ const w = {S}.spawnWall('brick'); w.pz = w.z = 960; {S}.walls.sort((a, b) => a.z - b.z); return w.id; }})()")
        await page.evaluate(f"{S}.smashTest('soft')"); await page.wait_for_timeout(150)
        cr = await page.evaluate(f"(() => {{ const w = {S}.walls.find(w => w.id === {w2}); return {{ left: w.left, n: w.bricks.length, cracked: w.bricks.filter(k => k.alive && k.hp < w.hp).length, dir: {S}.ball.dir }}; }})()")
        check('a soft hit only cracks a 2-hp brick and still bounces back', cr['left'] == cr['n'] and cr['cracked'] == 1 and cr['dir'] == 1, cr)
        await page.evaluate(f"{S}.walls.find(w => w.id === {w2}).pz = 960"); await page.evaluate(f"{S}.smashTest('hard')"); await page.wait_for_timeout(150)
        cr = await page.evaluate(f"(() => {{ const w = {S}.walls.find(w => w.id === {w2}); return {{ left: w.left, n: w.bricks.length, dir: {S}.ball.dir }}; }})()")
        check('a hard hit knocks 2-hp bricks out and passes', cr['n'] - cr['left'] >= 9 and cr['dir'] == -1, cr)
        await page.wait_for_timeout(200); await page.screenshot(path='tests/out/strike2_desktop.png')
        check('walls: no page errors', not errs, errs); await ctx.close()


        # --- wall kinds + spin (step 4), desktop mouse ---
        ctx = await b.new_context(viewport={'width':1280,'height':800}); page = await ctx.new_page(); await routes(page); errs=[]
        page.on('pageerror', lambda e: errs.append(str(e))); await page.add_init_script(INIT)
        await page.goto('http://localhost:8765/index.html'); await page.wait_for_timeout(600)
        await page.click('.modes button[data-mode=strike]'); await page.click('#mouseBtn'); await page.wait_for_timeout(900)
        await page.mouse.move(1200, 760); await page.wait_for_timeout(100)
        await page.evaluate("(() => { window.__sfx = []; const o = sfx; sfx = (k, a) => { __sfx.push(k); o(k, a); }; })()")  # every sound asked for, in order
        W_JS = lambda w: f"(() => {{ const w = {S}.walls.find(w => w.id === {w}); return {{ left: w.left, n: w.bricks.length, z: w.z, kind: w.kind, dents: w.bricks.filter(k => k.dent > 0).length, alive: w.bricks.filter(k => k.alive).length }}; }})()"
        check('level 1: every wall in the queue is brick, no tag yet', await page.evaluate(f"{S}.walls.every(w => w.kind === 'brick') && {S}.ui.tag === null && {S}.level === 1"))
        kinds = await page.evaluate("(() => { __grasp.strike.setLevel(1); const out = []; for (let i = 0; i < 12; i++) { const w = __grasp.strike.spawnWall(undefined, 9000 + i * 10); out.push(w.kind); __grasp.strike.walls.splice(__grasp.strike.walls.indexOf(w), 1); } return out; })()")
        check('level 1 mix: 12 spawned walls are all brick', kinds == ['brick'] * 12, kinds)
        kinds = await page.evaluate("(() => { __grasp.strike.setLevel(6); const out = [__grasp.strike.walls[0].kind]; for (let i = 0; i < 12; i++) { const w = __grasp.strike.spawnWall(undefined, 9000 + i * 10); out.push(w.kind); __grasp.strike.walls.splice(__grasp.strike.walls.indexOf(w), 1); } return out; })()")
        check('level 6 mix: the first wall of the level is TNT (the kind it unlocks), >= 3 kinds among 12 more, all known kinds', kinds[0] == 'tnt' and len(set(kinds[1:])) >= 3 and set(kinds) <= {'brick', 'glass', 'steel', 'holed', 'moving', 'tnt'}, kinds)
        lv = await page.evaluate("(() => { __grasp.strike.setLevel(3); const out = [__grasp.strike.walls[0].kind]; for (let i = 0; i < 20; i++) { const w = __grasp.strike.spawnWall(undefined, 9000 + i * 10); out.push(w.kind); __grasp.strike.walls.splice(__grasp.strike.walls.indexOf(w), 1); } return out; })()")
        check('level 3 mix: steel first, then only brick, glass and steel', lv[0] == 'steel' and set(lv) <= {'brick', 'glass', 'steel'}, lv)
        await page.evaluate(f"{S}.setLevel(1)"); await page.wait_for_timeout(50)
        check('setLevel(1): level 1 again, 4 brick walls in their slots', await page.evaluate(f"{S}.level === 1 && {S}.walls.length === 4 && {S}.walls.every(w => w.kind === 'brick' && w.hp === 1)"))
        # glass: pale blue translucent panes; any hit shatters 3x3 into many fine shards, the ball never bounces
        g = await page.evaluate(f"{S}.spawnWall('glass')"); await page.wait_for_timeout(80)
        check('spawnWall(glass): nearest slot, kind glass, 1-hp panes, tag "Glass wall!" shown under the HUD', g['kind'] == 'glass' and g['hp'] == 1 and abs(g['z'] - cfg['zf'] * 0.4) < 1 and await page.evaluate(f"{S}.walls.length === 4 && {S}.walls[0].id === {g['id']} && {S}.ui.tag && {S}.ui.tag.kind === 'glass'"), g['kind'])
        tb = await page.evaluate(f"{S}.ui.tagBox"); hud = await page.evaluate(f"{S}.ui.hud")
        check('the tag pill sits under the HUD card and names the kind', tb and tb['kind'] == 'glass' and tb['y'] >= hud['y'] + hud['h'] and tb['w'] > 60 and await page.evaluate("t('wk_glass')") == 'Glass wall!', tb)
        pt = await page.evaluate(f"{S}.brickScreen({S}.walls[0], 1, 1)"); px = await page.evaluate(PIX + f"({pt['x']}, {pt['y']})")
        check('glass pane drawn pale sky-blue (blue > red, bright)', px[2] > px[0] + 30 and px[2] > 120, px)
        await page.screenshot(path='tests/out/strike3_glass.png')
        s0 = await page.evaluate(f"{S}.score"); await page.evaluate(f"__sfx.length = 0; {S}.smashTest('soft')"); await page.wait_for_timeout(150)
        st = await page.evaluate(STATE); wl = await page.evaluate(W_JS(g['id']))
        check('glass: a soft hit shatters the 3x3 area and the ball flies on (no bounce)', wl['n'] - wl['left'] >= 6 and st['dir'] == -1 and st['z'] > wl['z'] and st['score'] - s0 >= 6, [st, wl])
        check('glass: many fine sparkling shards + glass tinkle', await page.evaluate(f"{S}.debris.length") >= 15 and await page.evaluate(f"{S}.debris.every(d => d.shard && d.k < 0.32)") and 'glass' in await page.evaluate("__sfx") and 'crack' not in await page.evaluate("__sfx"), await page.evaluate(f"[{S}.debris.length, __sfx]"))
        await page.wait_for_function(f"{S}.ball && {S}.ball.dir === 1", timeout=6000); await page.wait_for_timeout(200)
        # steel: riveted plates, 3 hp; soft / medium only dent + bounce; hard chips 1 hp; SUPER clears, 3 points a plate
        sw = await page.evaluate(f"{S}.spawnWall('steel')"); await page.wait_for_timeout(80)
        check('spawnWall(steel): 3-hp plates, tag "Steel wall!"', sw['kind'] == 'steel' and sw['hp'] == 3 and all(k['hp'] == 3 for k in sw['bricks']) and await page.evaluate(f"{S}.ui.tag.kind === 'steel'"))
        pt = await page.evaluate(f"{S}.brickScreen({S}.walls[0], 1, 1)"); px = await page.evaluate(PIX + f"({pt['x']}, {pt['y']})")
        check('steel plate drawn grey-blue', px[2] >= px[0] and abs(px[0] - px[1]) < 40 and 60 < px[2] < 200, px)
        s0 = await page.evaluate(f"{S}.score"); await page.evaluate(f"__sfx.length = 0; {S}.smashTest('medium')"); await page.wait_for_timeout(150)
        st = await page.evaluate(STATE); wl = await page.evaluate(W_JS(sw['id']))
        check('steel: a medium hit only dents 3x3 plates (crack overlay), clang, and the ball bounces back', wl['left'] == wl['n'] and wl['dents'] >= 6 and st['dir'] == 1 and st['z'] < wl['z'] and st['score'] == s0 and 'clang' in await page.evaluate("__sfx"), [st, wl, await page.evaluate("__sfx")])
        await page.evaluate(f"{S}.smashTest('hard')"); await page.wait_for_timeout(150)
        hp = await page.evaluate(f"(() => {{ const w = {S}.walls.find(w => w.id === {sw['id']}); return {{ left: w.left, n: w.bricks.length, chipped: w.bricks.filter(k => k.alive && k.hp === 2).length, dir: {S}.ball.dir, speed: {S}.speed, pace: {S}.pace }}; }})()")
        check('steel: a hard hit takes 1 hp off the plates it reaches (only the ones under the ball\'s footprint go), the ball goes on slowed', 1 <= hp['n'] - hp['left'] <= 5 and hp['chipped'] >= 6 and hp['dir'] == -1 and hp['speed'] < hp['pace'] * 1.5, hp)
        await page.wait_for_timeout(100); s0 = await page.evaluate(f"{S}.score"); n = hp['left']
        await page.evaluate(f"{S}.walls.forEach(w => {{ if (w.id !== {sw['id']}) w.left = 0; }})")  # the other walls stand aside: the SUPER ball must not score on them too
        await page.evaluate(f"{S}.smashTest('super')"); await page.wait_for_timeout(150)
        gone = await page.evaluate(f"!{S}.walls.some(w => w.id === {sw['id']})"); ds = await page.evaluate(f"{S}.score") - s0
        check('steel: SUPER removes every plate outright, 3 points each + the wall bonus', gone and ds == 3 * n + 10, [gone, ds, n])
        await page.evaluate(f"{S}.walls.forEach(w => (w.left = w.bricks.filter(k => k.alive).length))")
        await page.wait_for_function(f"{S}.ball && {S}.ball.dir === 1", timeout=6000); await page.wait_for_timeout(200)
        # holed: a 1-2 brick gap with glowing edges; the ball flies through it untouched
        hw = await page.evaluate(f"{S}.spawnWall('holed')"); await page.wait_for_timeout(80)
        holes = [k for k in hw['bricks'] if k['hole']]
        check('spawnWall(holed): a 1-2 brick hole, those bricks dead, left counts the rest, tag', hw['kind'] == 'holed' and 1 <= len(holes) <= 2 and all(not k['alive'] for k in holes) and hw['left'] == hw['bricks'].__len__() - len(holes) and await page.evaluate(f"{S}.ui.tag.kind === 'holed'"), [len(holes), hw['left']])
        hc = holes[0]; await page.evaluate(f"{S}.setBallZ(2300, 30, 30); {S}.walls.slice(1).forEach(w => (w.pz = w.z = 3200))"); await page.wait_for_timeout(80)  # the ball and the walls behind out of the probes (the queue slides back on its own)
        pt = await page.evaluate(f"{S}.brickScreen({S}.walls[0], {hc['col']}, {hc['row']})"); edge = [0, 0, 0]
        for _ in range(8):  # the glow pulses over ~1 s: keep the most saffron sample
            e = await page.evaluate(PIX + f"({pt['x'] - pt['w'] / 2 + pt['w'] * 0.05}, {pt['y']})"); edge = max(edge, e, key=lambda c: c[0] - c[2]); await page.wait_for_timeout(70)
        mid = await page.evaluate(PIX + f"({pt['x']}, {pt['y']})")
        check('hole edges glow saffron, the hole itself shows the corridor', edge[0] > 150 and edge[1] > 100 and edge[0] > edge[2] + 40 and sum(mid) < 260, [edge, mid])
        s0 = await page.evaluate(f"{S}.score"); await page.evaluate(f"__sfx.length = 0; {S}.smashTest('soft', {hc['col']}, {hc['row']})"); await page.wait_for_timeout(150)
        st = await page.evaluate(STATE); wl = await page.evaluate(W_JS(hw['id']))
        check('a soft ball aimed at the hole passes through with no damage and a whoosh', wl['left'] == hw['left'] and st['dir'] == -1 and st['z'] > wl['z'] and st['score'] == s0 and 'whoosh' in await page.evaluate("__sfx") and 'crack' not in await page.evaluate("__sfx"), [st, wl, await page.evaluate("__sfx")])
        await page.evaluate(f"{S}.smashTest('medium', {hc['col']}, {hc['row']})"); await page.wait_for_timeout(150)
        wl = await page.evaluate(W_JS(hw['id']))
        check('a medium ball through the hole: still no damage', wl['left'] == hw['left'] and await page.evaluate(f"{S}.ball.dir === -1"), wl)
        await page.evaluate(f"{S}.setBallZ(1500, 640, 400)")
        # moving: one column narrower, slides side to side on a slow sine
        mw = await page.evaluate(f"{S}.spawnWall('moving')"); grid = await page.evaluate(f"(() => {{ const w = {S}.walls[1]; return {{ cols: w.cols, span: w.span }}; }})()")
        check('spawnWall(moving): cols - 1 wide, span = the full grid, tag', mw['kind'] == 'moving' and mw['cols'] == mw['span'] - 1 and mw['span'] == grid['span'] and await page.evaluate(f"{S}.ui.tag.kind === 'moving'"), [mw['cols'], mw['span'], grid])
        ox0 = await page.evaluate(f"{S}.walls[0].ox"); x0 = (await page.evaluate(f"{S}.brickScreen({S}.walls[0], 0, 0)"))['x']; await page.wait_for_timeout(400)
        ox1 = await page.evaluate(f"{S}.walls[0].ox"); x1 = (await page.evaluate(f"{S}.brickScreen({S}.walls[0], 0, 0)"))['x']; cw = (await page.evaluate(f"{S}.brickScreen({S}.walls[0], 0, 0)"))['w']
        check('moving wall slides: its x offset and the bricks on screen move over 400 ms, within one brick width', ox0 != ox1 and abs(x1 - x0) > 1 and 0 <= ox0 <= cw / (await page.evaluate(f"STRIKE_F / (STRIKE_F + {S}.walls[0].z)")) + 1 and 0 <= ox1, [ox0, ox1, x0, x1])
        await page.screenshot(path='tests/out/strike3_moving.png')
        # TNT: 2-3 red crates; breaking one blows a radius-2 area, chains into another crate inside it
        tw = await page.evaluate(f"{S}.spawnWall('tnt')"); crates = [k for k in tw['bricks'] if k['tnt']]
        check('spawnWall(tnt): 2-3 TNT crates (1 hp), the rest bricks, tag', tw['kind'] == 'tnt' and 2 <= len(crates) <= 3 and all(k['hp'] == 1 for k in crates) and await page.evaluate(f"{S}.ui.tag.kind === 'tnt'"), len(crates))
        await page.evaluate(f"(() => {{ const w = {S}.walls.find(w => w.id === {tw['id']}); w.bricks.forEach(k => {{ k.tnt = false; k.hp = w.hp; }}); for (const [c, r] of [[1, 1], [2, 2]]) {{ const k = w.bricks.find(k => k.col === c && k.row === r); k.tnt = true; k.hp = 1; }} }})()"); await page.wait_for_timeout(60)  # a deterministic pair, two apart on the diagonal
        pt = await page.evaluate(f"{S}.brickScreen({S}.walls[0], 1, 1)"); px = await page.evaluate(PIX + f"({pt['x'] - pt['w'] * 0.3}, {pt['y'] - pt['h'] * 0.3})")
        check('TNT crate drawn red (under the depth fog)', px[0] > 100 and px[0] > px[1] + 50 and px[0] > px[2] + 40, px)
        await page.screenshot(path='tests/out/strike3_tnt.png')
        s0 = await page.evaluate(f"{S}.score"); e0 = await page.evaluate(f"{S}.explosions"); await page.evaluate(f"{S}.smashTest('soft', 1, 1)"); await page.wait_for_timeout(120)
        wl = await page.evaluate(W_JS(tw['id'])) if await page.evaluate(f"{S}.walls.some(w => w.id === {tw['id']})") else None
        ex = await page.evaluate(f"({{ n: {S}.explosions, age: performance.now() - {S}.tntAt, shake: shake.amp }})")
        check('a soft hit on a crate: explosion clears the radius-2 area and chains into the second crate (2 booms)', ex['n'] - e0 == 2 and (wl is None or wl['n'] - wl['left'] >= 14) and await page.evaluate(f"{S}.score") - s0 >= 14, [ex, wl])
        check('TNT: orange flash, rings and a big shake', ex['age'] < 400 and ex['shake'] >= 3 and await page.evaluate("rings.length") >= 2, ex)
        await page.wait_for_timeout(150); await page.screenshot(path='tests/out/strike3_boom.png')
        await page.wait_for_timeout(500); fpsv = await page.evaluate("fps")
        check('frame rate holds through the explosion, debris and shards', fpsv >= 30, round(fpsv))
        await page.wait_for_function(f"{S}.ball && {S}.ball.dir === 1", timeout=6000); await page.wait_for_timeout(200)
        # spin: an off-centre slap curves the ball; a side-wall ricochet mirrors the spin and sparks
        await page.evaluate(f"{S}.walls.forEach(w => (w.left = 0))")  # the walls stand aside for the flight
        await page.mouse.move(640, 400); await page.wait_for_timeout(250)
        await page.evaluate(hit_js(640, 400, 50)); await page.wait_for_timeout(60)
        c0 = await page.evaluate(f"({{ spin: {S}.ball.spin, vx: {S}.ball.vx, lh: {S}.lastHit, speed: {S}.speed, pace: {S}.pace }})")
        check('dead-centre slap: near-zero spin and lateral speed, a straight fast ball (speed bonus)', abs(c0['spin']) < 0.25 and abs(c0['lh']['offx']) < 0.15 and c0['speed'] > c0['pace'] * (0.55 + 1.45 * c0['lh']['pw']) * 1.02, c0)
        await page.evaluate(f"{S}.setBallZ(1500, 640, 400)"); await page.wait_for_timeout(250)
        r0 = await page.evaluate(f"{S}.ricochets"); await page.evaluate(hit_js(600, 400)); await page.wait_for_timeout(50)  # the cursor sits 40 px right of the ball's centre
        c1 = await page.evaluate(f"({{ spin: {S}.ball.spin, vx: {S}.ball.vx, z: {S}.ball.z, dir: {S}.ball.dir, rot: {S}.ball.rot }})"); await page.wait_for_timeout(300)
        c2 = await page.evaluate(f"({{ spin: {S}.ball.spin, vx: {S}.ball.vx, z: {S}.ball.z, dir: {S}.ball.dir, rot: {S}.ball.rot, ric: {S}.ricochets - {r0} }})")
        check('off-centre slap: the ball goes left with spin > 0, and the spin curves it (vx drifts back toward the right over the flight, no ricochet)', c1['dir'] == -1 and c1['vx'] < 0 and c1['spin'] > 0.1 and c2['dir'] == -1 and c2['spin'] == c1['spin'] and c2['vx'] - c1['vx'] > 0.01 and c2['ric'] == 0, [c1, c2])
        check('the ball sprite turns with the spin (rotation runs on)', c2['rot'] != c1['rot'] and await page.evaluate("[...SPRITES.keys()].some(k => k === 'strikeBall|0|s')"))
        await page.screenshot(path='tests/out/strike3_spin.png')
        await page.evaluate(f"{S}.setBallZ(1500, 640, 400)"); await page.wait_for_timeout(250)
        await page.mouse.move(380, 400); await page.wait_for_timeout(200); r0 = await page.evaluate(f"{S}.ricochets"); n0 = await page.evaluate("particles.length")
        await page.evaluate("__sfx.length = 0; " + hit_js(300, 400)); await page.wait_for_timeout(40)  # slapped on its right side, 100-odd px from the left wall
        sp0 = await page.evaluate(f"{S}.ball.spin"); vx0 = await page.evaluate(f"{S}.ball.vx")
        await page.wait_for_function(f"{S}.ricochets > {r0}", timeout=3000); await page.wait_for_timeout(30)
        rc = await page.evaluate(f"({{ spin: {S}.ball.spin, vx: {S}.ball.vx, ric: {S}.ricochets, sfx: __sfx, parts: particles.length, dir: {S}.ball.dir }})")
        check('slapped hard toward the left wall: ricochet sparks + ping, vx mirrored, spin mirrored', sp0 > 0 and vx0 < 0 and rc['ric'] == r0 + 1 and rc['spin'] == -sp0 and rc['vx'] > 0 and 'ricochet' in rc['sfx'] and rc['parts'] > n0 and rc['dir'] == -1, [sp0, vx0, rc])
        await page.evaluate(f"{S}.walls.forEach(w => (w.left = w.bricks.filter(k => k.alive).length))")
        # the ball never looks as if it went behind a wall: a pass-through leaves a ball-sized hole, a just-passed wall is drawn behind the ball, a bounce keeps it in front
        await page.evaluate(f"{S}.setLevel(1)"); bw = await page.evaluate(f"{S}.spawnWall('brick')"); await page.evaluate(f"{S}.setBallZ(1500, 640, 400)"); await page.wait_for_timeout(200)
        await page.evaluate(f"{S}.smashTest('soft')"); await page.wait_for_function(f"{S}.ball.dir === 1", timeout=2000)
        bz = await page.evaluate(f"({{ z: {S}.ball.z, wz: {S}.walls.find(w => w.id === {bw['id']}).z, r: ballR() }})")
        check('a bounce leaves the ball a ball\'s depth in front of the wall, never inside it', bz['z'] <= bz['wz'] - bz['r'] + 1, bz)
        await page.evaluate(f"{S}.walls.find(w => w.id === {bw['id']}).pz = {bz['wz']}")
        await page.evaluate(f"(() => {{ const w = {S}.smashTest('medium'); window.__hit = {{ x: {S}.ball.x, y: {S}.ball.y, id: w.id }}; }})()"); await page.wait_for_timeout(150)
        fp = await page.evaluate(f"(() => {{ const w = {S}.walls.find(w => w.id === __hit.id), r = ballR() * 1.1, h = __hit; return {{ dir: {S}.ball.dir, z: {S}.ball.z, wz: w.z, gone: w.bricks.length - w.left, over: w.bricks.filter((k) => {{ if (!k.alive) return false; const c = brickCell(w, k.col, k.row); return Math.hypot(Math.max(0, Math.abs(h.x - c.x) - c.w / 2), Math.max(0, Math.abs(h.y - c.y) - c.h / 2)) < r; }}).length }}; }})()")
        check('a medium pass-through clears every brick the ball\'s footprint overlaps (hole at least ball-sized)', fp['dir'] == -1 and fp['z'] > fp['wz'] and fp['gone'] >= 6 and fp['over'] == 0, fp)
        await page.wait_for_function(f"{S}.ball && {S}.ball.dir === 1", timeout=6000); await page.wait_for_timeout(100)
        iw = await page.evaluate(f"{S}.spawnWall('brick')"); await page.evaluate(f"{S}.setBallZ(1500, 640, 400)"); await page.wait_for_timeout(200)  # an intact wall; the ball parked just past it, flying away
        await page.evaluate(f"(() => {{ const w = {S}.walls.find(w => w.id === {iw['id']}), b = {S}.ball, c = brickCell(w, 1, 1); b.dir = -1; b.x = c.x; b.y = c.y; b.vx = b.vy = 0; b.z = w.z + 8; b.tier = 'hard'; {S}.speed = {S}.pace; }})()"); await page.wait_for_timeout(40)
        bs = await page.evaluate(f"{S}.ballScreen()"); px = await page.evaluate(PIX + f"({bs['x']}, {bs['y']})"); ov = await page.evaluate(f"({{ over: {S}.ui.ballOver, z: {S}.ball.z, wz: {S}.walls.find(w => w.id === {iw['id']}).z }})")
        check('just past a wall the ball is drawn on top of it: ball colour at its centre, the wall listed as drawn behind it', ov['z'] > ov['wz'] and iw['id'] in ov['over'] and px[0] > 170 and px[0] > px[2] + 40, [ov, px])
        await page.evaluate(f"{S}.ball.z = {ov['wz']} + __grasp.CONFIG.STRIKE_WALL_GAP * 0.3"); await page.wait_for_timeout(40)
        check('further on, the wall is in front of the ball again (ordinary depth order)', await page.evaluate(f"{S}.ui.ballOver.length === 0"))
        await page.evaluate(f"{S}.setBallZ(1500, 640, 400)")
        check('kinds: no page errors', not errs, errs); await ctx.close()
        # --- in-game UI (step 3): HUD card, power meter, combo banner, serve cue, round-over card ---
        ctx = await b.new_context(viewport={'width':1280,'height':800}); page = await ctx.new_page(); await routes(page); errs=[]
        page.on('pageerror', lambda e: errs.append(str(e))); await page.add_init_script(INIT)
        await page.goto('http://localhost:8765/index.html'); await page.wait_for_timeout(600)
        await page.click('.modes button[data-mode=strike]'); await page.click('#mouseBtn'); await page.wait_for_timeout(900)
        await page.mouse.move(1200, 760); await page.wait_for_timeout(200)
        chrome = await page.evaluate("document.querySelector('.chrome').getBoundingClientRect().bottom"); hud = await page.evaluate(f"{S}.ui.hud")
        check('HUD card sits below the chrome buttons and fits the screen', hud and hud['y'] >= chrome and hud['x'] >= 0 and hud['x'] + hud['w'] <= 1280 and hud['h'] >= 48, [hud, chrome])
        rim = await page.evaluate(PIX + f"({hud['x'] + hud['w'] / 2}, {hud['y']})"); above = await page.evaluate(PIX + f"({hud['x'] + hud['w'] / 2}, {hud['y'] - 4})")
        check('HUD card rim drawn (a lighter line than the corridor above it)', sum(rim) > sum(above) + 30, [rim, above])
        hearts = await page.evaluate(f"{S}.ui.hearts"); hp = await page.evaluate(PIX + f"({hearts[0]['x']}, {hearts[0]['y']})")
        check('all hearts full on the card', len(hearts) == cfg['lives'] and hp[0] > 170 and hp[0] > hp[2] + 60 and all(hud['y'] < h['y'] < hud['y'] + hud['h'] for h in hearts), [hearts, hp])
        await page.evaluate(f"{S}.score += 100; {S}.ui.scoreAt = performance.now()"); await page.wait_for_timeout(60)
        shown = await page.evaluate(f"{S}.ui.shown")
        check('score counts up over time rather than jumping', 0 < shown < 100, shown)
        await page.wait_for_timeout(900)
        check('count-up settles on the score', await page.evaluate(f"{S}.ui.shown === {S}.score && Math.round({S}.ui.shown) === 100"))
        # power meter: fills with the hand speed before any hit, live tier name, back to empty when the hand rests
        await page.mouse.move(640, 600); await page.wait_for_timeout(700)
        m0 = await page.evaluate(f"{S}.ui.meter")
        await page.evaluate("(() => { const now = performance.now(); cursor.history.length = 0; cursor.history.push({ t: now - 60, x: 440, y: 600 }, { t: now, x: 640, y: 600 }); })()"); await page.wait_for_timeout(50)
        m1 = await page.evaluate(f"({{ v: {S}.ui.meter, tier: {S}.ui.meterTier }})")
        await page.wait_for_timeout(700); m2 = await page.evaluate(f"{S}.ui.meter")
        check('meter follows the hand speed: empty at rest, high after a fast move, empty again', m0 < 0.05 and m1['v'] > 0.4 and m1['tier'] in ('hard', 'super') and m2 < 0.08, [m0, m1, m2])
        await page.evaluate(hit_js(640, 600, 50)); await page.wait_for_timeout(100)
        tf = await page.evaluate(f"({{ tier: {S}.ui.tierFlash.tier, age: performance.now() - {S}.ui.tierFlash.t, txt: {S}.floaters.map(f => f.text) }})")
        check('medium hit: tier label flashes on the meter, the floater only shows the points', tf['tier'] == 'medium' and tf['age'] < 600 and any(x == '+2' for x in tf['txt']) and not any('Medium' in x for x in tf['txt']), tf)
        await page.screenshot(path='tests/out/strike_ui_desktop.png')
        # combo banner on the second SUPER wall
        await page.mouse.move(1200, 760); await page.wait_for_timeout(700)
        await page.evaluate(f"{S}.smashTest('super')")
        await page.wait_for_function(f"{S}.ui.banner && {S}.ui.banner.n >= 2", timeout=4000)
        bn = await page.evaluate(f"({{ n: {S}.ui.banner.n, age: performance.now() - {S}.ui.banner.t }})")
        check('SUPER second wall: combo banner active', bn['n'] >= 2 and bn['age'] < 900, bn)
        await page.wait_for_timeout(200); await page.screenshot(path='tests/out/strike_ui_combo.png')
        await page.wait_for_function(f"{S}.ball && {S}.ball.dir === 1", timeout=5000)
        # miss: lost heart shakes then stays hollow; serve cue before the next ball
        lv = await page.evaluate(f"{S}.lives"); await miss(page)
        hl = await page.evaluate(f"{S}.ui.heartLost")
        check('miss: the heart that went hollow is the last full one', hl and hl['i'] == lv - 1 and await page.evaluate(f"{S}.lives") == lv - 1, [hl, lv])
        await page.wait_for_timeout(200)
        cue = await page.evaluate(f"({{ k: {S}.ui.cue, cued: {S}.cued, ball: !!{S}.ball }})")
        check('serve cue: ring at the far end (+ whoosh) 500 ms before the serve', cue['k'] is not None and 0 <= cue['k'] < 1 and cue['cued'] and not cue['ball'], cue)
        await page.wait_for_timeout(500)
        hearts = await page.evaluate(f"{S}.ui.hearts"); h0 = await page.evaluate(PIX + f"({hearts[0]['x']}, {hearts[0]['y']})"); h2 = await page.evaluate(PIX + f"({hearts[hl['i']]['x']}, {hearts[hl['i']]['y']})")
        check('hearts: first still red, the lost one hollow after the miss', h0[0] > 170 and h0[0] > h0[2] + 60 and h2[0] < 120, [h0, h2])
        # round over card: NEW BEST ribbon, stats, buttons
        await miss_out(page, cfg['lives'] - 1)
        await page.wait_for_function(f"{S}.over && {S}.ui.buttons", timeout=3000); await page.wait_for_timeout(600)
        ov = await page.evaluate(f"({{ nb: {S}.ui.newBest, best: {S}.best, score: {S}.score, rb: {S}.ui.ribbon, bt: {S}.ui.buttons, hits: {S}.hits, walls: {S}.cleared, combo: {S}.bestCombo }})")
        rbp = await page.evaluate(PIX + f"({ov['rb']['x']}, {ov['rb']['y']})") if ov['rb'] else None
        check('round over with a NEW BEST ribbon (saffron pixel on the card corner)', ov['nb'] and ov['best'] == ov['score'] > 0 and rbp and rbp[0] > 200 and rbp[1] > 140 and rbp[2] < 130, [ov, rbp])
        check('stats for the card: hits, walls, best combo', ov['hits'] >= 1 and ov['walls'] >= 2 and ov['combo'] >= 2, ov)
        bt = ov['bt']
        check('two buttons on the card, side by side, on screen', bt['again']['w'] > 100 and bt['home']['w'] > 100 and bt['again']['y'] == bt['home']['y'] and bt['again']['x'] + bt['again']['w'] < bt['home']['x'] and bt['home']['x'] + bt['home']['w'] <= 1280, bt)
        ab = await page.evaluate(PIX + f"({bt['again']['x'] + 12}, {bt['again']['y'] + bt['again']['h'] / 2})")
        check('Play again button is saffron', ab[0] > 200 and ab[1] > 150 and ab[2] < 130, ab)
        await page.screenshot(path='tests/out/strike_ui_over.png')
        await page.mouse.click(bt['again']['x'] + bt['again']['w'] / 2, bt['again']['y'] + bt['again']['h'] / 2); await page.wait_for_timeout(200)
        st = await page.evaluate(STATE)
        check('click Play again: fresh round, best kept', not st['over'] and st['score'] == 0 and st['lives'] == cfg['lives'] and st['best'] == ov['best'] and await page.evaluate(f"{S}.ui.buttons === null"), st)
        await page.mouse.move(1200, 760); await page.wait_for_timeout(700)
        await miss_out(page, cfg['lives'])
        await page.wait_for_function(f"{S}.over && {S}.ui.buttons", timeout=3000); await page.wait_for_timeout(600)
        check('a worse round: no NEW BEST', await page.evaluate(f"!{S}.ui.newBest && {S}.ui.ribbon === null"))
        # point gesture (right button) dwelling on Home for 400 ms presses it via the filling ring
        bt = await page.evaluate(f"{S}.ui.buttons")
        await page.mouse.move(bt['home']['x'] + bt['home']['w'] / 2, bt['home']['y'] + bt['home']['h'] / 2); await page.wait_for_timeout(100)
        check('hovering the Home button highlights it', await page.evaluate(f"{S}.ui.hover") == 'home')
        await page.mouse.down(button='right'); await page.wait_for_timeout(200)
        dw = await page.evaluate(f"({S}.ui.dwell && {S}.ui.dwell.key)"); still = await page.evaluate("mode")
        await page.wait_for_timeout(400); await page.mouse.up(button='right')
        check('point held on Home: dwell ring fills, then Home fires (no instant restart)', dw == 'home' and still == 'mouse' and await page.evaluate("mode === 'none' && !$('start').hidden"), [dw, still, await page.evaluate("mode")])
        # tap on Home from a fresh round-over
        await page.click('#mouseBtn'); await page.wait_for_timeout(500); await page.mouse.move(1200, 760); await page.wait_for_timeout(300)
        await miss_out(page, cfg['lives'])
        await page.wait_for_function(f"{S}.over && {S}.ui.buttons", timeout=3000); await page.wait_for_timeout(600)
        bt = await page.evaluate(f"{S}.ui.buttons")
        await page.mouse.click(bt['home']['x'] + bt['home']['w'] / 2, bt['home']['y'] + bt['home']['h'] / 2); await page.wait_for_timeout(200)
        check('click Home: back to the start screen', await page.evaluate("mode === 'none' && !$('start').hidden && document.body.classList.contains('home')"))
        check('ui: no page errors', not errs, errs); await ctx.close()

        # --- camera stub, desktop: an open hand on the ball hits it ---
        ctx = await b.new_context(permissions=['camera'], viewport={'width':1280,'height':800}); page = await ctx.new_page(); await routes(page); errs=[]
        page.on('pageerror', lambda e: errs.append(str(e))); await page.add_init_script(INIT + HAND_JS)
        await page.goto('http://localhost:8765/index.html'); await page.wait_for_timeout(600)
        await page.click('.modes button[data-mode=strike]'); await page.click('#camBtn')
        await page.wait_for_function("mode === 'camera'", timeout=15000)
        await page.evaluate("window.__handFor = () => handAt(640, 400, 0.8)"); await page.wait_for_timeout(900)
        cur = await page.evaluate("[gesture, cursor.x, cursor.y, cursor.present]")
        check('camera: open hand tracked as the cursor', cur[0] == 'open' and cur[3] and abs(cur[1] - 640) < 30 and abs(cur[2] - 400) < 30, cur)
        await page.evaluate(f"{S}.setBallZ(__grasp.CONFIG.STRIKE_HIT_Z, cursor.x, cursor.y)"); await page.wait_for_timeout(120)
        st = await page.evaluate(STATE)
        check('camera: open hand at the ball position hits it', st['dir'] == -1 and st['score'] >= 1, st)
        await page.wait_for_timeout(40); await page.screenshot(path='tests/out/strike_camera.png')
        await page.evaluate("window.__handFor = () => null"); await page.wait_for_timeout(700)
        z0 = await page.evaluate(f"{S}.ball && {S}.ball.z"); await page.wait_for_timeout(300); z1 = await page.evaluate(f"{S}.ball && {S}.ball.z")
        check('camera: the ball waits while the hand is missing', await page.evaluate("noHandShown") and z0 == z1, [z0, z1])
        check('camera: no page errors', not errs, errs); await ctx.close()

        # --- phone (touch), English + Hebrew ---
        for he in (False, True):
            tag = 'he' if he else 'en'
            ctx = await b.new_context(viewport={'width':360,'height':740}, device_scale_factor=3, is_mobile=True, has_touch=True); page = await ctx.new_page(); await routes(page); errs=[]
            page.on('pageerror', lambda e: errs.append(str(e))); await page.add_init_script(INIT + TOUCH_JS)
            await page.goto('http://localhost:8765/index.html'); await page.wait_for_timeout(600)
            if he: await page.tap('#startLang'); await page.wait_for_timeout(100)
            rows = await page.evaluate(ROWS)
            check(tag + ' phone: 5 mode cards in one snap row and link fit', await page.evaluate(FITS) and rows == 1, rows)
            await page.screenshot(path='tests/out/strike_start_' + tag + '.png')
            await page.tap('.modes button[data-mode=strike]')
            check(tag + ' phone: strike description', await page.evaluate("$('modeDesc').textContent.includes(" + ("'מסדרון'" if he else "'corridor'") + ")"))
            await page.tap('#mouseBtn'); await page.wait_for_timeout(900)
            st = await page.evaluate(STATE)
            check(tag + ' phone: ball served', st['z'] is not None and st['lives'] == cfg['lives'], st)
            dp = await page.evaluate("(() => { const d = $('strikeDiff'); return { hidden: d.hidden, txt: [...d.querySelectorAll('button')].map(b => b.textContent + ':' + b.getAttribute('aria-pressed')) }; })()")
            check(tag + ' phone: Easy / Normal pill was shown on the start screen with Easy selected', not dp['hidden'] and dp['txt'] == (['קל:true', 'רגיל:false'] if he else ['Easy:true', 'Normal:false']), dp)
            await page.evaluate("touchAt('pointerdown', 180, 360)"); await page.wait_for_timeout(80)
            await page.evaluate(f"{S}.setBallZ(700, 180, 360)"); await page.wait_for_timeout(50)
            await page.screenshot(path='tests/out/strike_phone_' + tag + '.png')
            await page.evaluate(hit_js(180, 360, 50)); await page.wait_for_timeout(120)  # ~0.85-1.1 px/ms at the phone's 0.55 scale = hard (60 px sat on the SUPER edge: the next frame's rAF timestamp trails performance.now() by 0-16 ms)
            st = await page.evaluate(STATE)
            check(tag + ' phone: a finger on the ball hits it', st['dir'] == -1 and st['score'] >= 1 and st['lives'] == cfg['lives'], st)
            await page.screenshot(path='tests/out/strike_ui_' + tag + '.png')
            hud = await page.evaluate(f"{S}.ui.hud"); chrome = await page.evaluate("document.querySelector('.chrome').getBoundingClientRect().bottom")
            check(tag + ' phone: HUD card under the chrome, inside 360 px', hud['y'] >= chrome and hud['x'] >= 8 and hud['x'] + hud['w'] <= 352, [hud, chrome])
            check(tag + ' phone: tier flash on the meter after the hit', await page.evaluate(f"{S}.ui.tierFlash && {S}.ui.tierFlash.tier === 'hard'"))
            await page.evaluate("touchAt('pointerup', 180, 360)"); await page.wait_for_timeout(300)
            check(tag + ' phone: hint mentions the walls', ('לבנים' if he else 'walls') in await page.inner_text('#hint'))
            mixed = await page.evaluate(f"(() => {{ const s = {S}; s.setLevel(6); s.walls.length = 0; s.seenKinds.clear(); ['tnt', 'steel', 'holed'].forEach((k, i) => s.spawnWall(k, __grasp.CONFIG.STRIKE_Z_FAR * 0.4 + (i + 1) * __grasp.CONFIG.STRIKE_WALL_GAP)); s.spawnWall('glass'); s.setBallZ(600, 180, 300); return s.walls.map(w => w.kind); }})()"); await page.wait_for_timeout(120)
            tb = await page.evaluate(f"{S}.ui.tagBox")
            check(tag + ' phone: a mixed queue of wall kinds, "' + ('קיר זכוכית!' if he else 'Glass wall!') + '" tag under the HUD inside the screen', mixed[0] == 'glass' and set(mixed) >= {'tnt', 'steel', 'holed'} and tb and tb['kind'] == 'glass' and tb['x'] >= 8 and tb['x'] + tb['w'] <= 352 and await page.evaluate("t('wk_glass')") == ('קיר זכוכית!' if he else 'Glass wall!'), [mixed, tb])
            await page.screenshot(path='tests/out/strike3_phone_' + tag + '.png')
            await page.evaluate(f"{S}.setLevel(1)"); await page.wait_for_timeout(50)
            await page.evaluate(f"{S}.setBallZ(1500, 180, 300)"); await page.wait_for_timeout(100)
            await page.evaluate(f"(() => {{ const w = {S}.smashTest('medium'); window.__hit = {{ x: {S}.ball.x, y: {S}.ball.y, id: w.id }}; }})()"); await page.wait_for_timeout(150)
            fp = await page.evaluate(f"(() => {{ const w = {S}.walls.find(w => w.id === __hit.id), r = ballR() * 1.1, h = __hit; return {{ dir: {S}.ball.dir, cell: [Math.round(brickCell(w, 0, 0).w), Math.round(brickCell(w, 0, 0).h)], r: Math.round(ballR()), gone: w.bricks.length - w.left, over: w.bricks.filter((k) => {{ if (!k.alive) return false; const c = brickCell(w, k.col, k.row); return Math.hypot(Math.max(0, Math.abs(h.x - c.x) - c.w / 2), Math.max(0, Math.abs(h.y - c.y) - c.h / 2)) < r; }}).length }}; }})()")
            check(tag + ' phone: a medium pass on the small phone bricks leaves a ball-sized hole (no live brick under the ball)', fp['dir'] == -1 and fp['gone'] >= 6 and fp['over'] == 0, fp)
            await page.wait_for_function(f"{S}.ball && {S}.ball.dir === 1", timeout=6000)
            s0 = await page.evaluate(f"{S}.score"); await page.evaluate(f"{S}.smashTest('super')"); await page.wait_for_timeout(140)
            await page.screenshot(path='tests/out/strike2_phone_' + tag + '.png')
            check(tag + ' phone: SUPER smash clears a wall with debris', await page.evaluate(f"{S}.cleared") >= 1 and await page.evaluate(f"{S}.debris.length") > 0 and await page.evaluate(f"{S}.score") - s0 >= 20)
            await page.wait_for_timeout(300)
            await miss_out(page, cfg['lives'])
            check(tag + ' phone: round over after all lives are missed', await page.evaluate(f"{S}.over"))
            await page.wait_for_timeout(600); await page.screenshot(path='tests/out/strike_over_' + tag + '.png')
            bt = await page.evaluate(f"{S}.ui.buttons")
            check(tag + ' phone: card buttons fit the screen' + (', Play again on the right' if he else ''), bt and all(b['x'] >= 8 and b['x'] + b['w'] <= 352 and b['h'] >= 44 for b in bt.values()) and ((bt['again']['x'] > bt['home']['x']) == he), bt)
            check(tag + ' phone: Easy / Normal pill on the card, Easy at the start edge', 'easy' in bt and 'normal' in bt and ((bt['easy']['x'] > bt['normal']['x']) == he) and bt['easy']['y'] > bt['again']['y'], bt)
            await page.tap('#stage', position={'x': bt['normal']['x'] + bt['normal']['w'] / 2, 'y': bt['normal']['y'] + bt['normal']['h'] / 2}); await page.wait_for_timeout(200)
            check(tag + ' phone: tapping Normal on the card switches the difficulty without restarting', await page.evaluate(f"{S}.diff === 'normal' && {S}.over && localStorage.getItem('strikeDiff') === 'normal'"))
            await page.tap('#stage', position={'x': bt['again']['x'] + bt['again']['w'] / 2, 'y': bt['again']['y'] + bt['again']['h'] / 2}); await page.wait_for_timeout(200)
            check(tag + ' phone: Play again starts a Normal round with 3 lives', await page.evaluate(f"!{S}.over && {S}.lives === 3"))
            await page.evaluate("__grasp.setGameMode('strike'); __grasp.setStrikeDiff('easy')")
            check(tag + ' phone: no page errors', not errs, errs); await ctx.close()
        await b.close()
    print('FAILURES:', check.fails)
asyncio.run(main()); srv.terminate()
if check.fails: sys.exit(1)
